// Generated by PhysureScript (PHS) Compiler v0.2.4
use physure_core::Quantity;

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let g = Quantity::with_uncertainty(9.81, 0.05, "m / s ^ 2").unwrap();
    println!("g: {}", g);
    let m1 = Quantity::with_uncertainty(10.0, 0.1, "kg").unwrap();
    println!("m1: {}", m1);
    let f = m1 * g;
    println!("f: {}", f);
    Ok(())
}
