// Generated by PhysureScript (PHS) Compiler v0.2.4
import com.physure.Quantity;
import com.physure.PhyEquation;
import com.physure.PhyFunction;
import java.util.*;

public class Main {
    public static void main(String[] args) {
        Quantity g = Quantity.withUncertainty(9.81, 0.05, "m / s ^ 2");
        System.out.println("g: " + g);
        Quantity m1 = Quantity.withUncertainty(10.0, 0.1, "kg");
        System.out.println("m1: " + m1);
        Quantity f = m1.multiply(g);
        System.out.println("f: " + f);
    }
}
