# Generated by PhysureScript (PHS) Compiler v0.2.4
import math
from physure import Q_, Quantity, PhyEquation, PhyFunction, phy_function

try:
    from physure.builtins import vector, gradient, trapz, solve, deriv, integral
except ImportError:
    def vector(*args): return list(args)

g = Q_(9.81, "m / s ^ 2", uncertainty=0.05)
print(f"g: {g}")
m1 = Q_(10.0, "kg", uncertainty=0.1)
print(f"m1: {m1}")
f = (m1 * g)
print(f"f: {f}")
