# measurekit_core.pyi
# Typing stub for the native Rust core module of MeasureKit.

from typing import Any

class RationalUnit:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...

class UnitRegistry:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...

class Quantity:
    _core_magnitude: Any
    _core_unit: Any
    _core_uncertainty: Any
    magnitude: Any
    unit: Any
    std_dev: Any
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...

class CovarianceStore:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...

class PruningConfig:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...

def to_arrow_record_batch(*args: Any, **kwargs: Any) -> Any: ...
