# physure_core.pyi
# Typing stub for the native Rust core module of Physure.

from typing import Any

from typing_extensions import Self

class RationalUnit:
    def __new__(cls, *args: Any, **kwargs: Any) -> Self: ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
    def __mul__(self, other: RationalUnit) -> RationalUnit: ...
    def __truediv__(self, other: RationalUnit) -> RationalUnit: ...
    def __pow__(
        self, exponent: int | tuple[int, int], modulo: Any | None = ...
    ) -> RationalUnit: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class UnitRegistry:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...

class Quantity:
    _core_magnitude: Any
    _core_unit: Any
    _core_uncertainty: Any
    magnitude: Any
    unit: Any
    std_dev: Any
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...

class CovarianceStore:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...

class PruningConfig:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...

class DimVector:
    def __init__(self, pairs: dict[str, int]) -> None: ...
    @staticmethod
    def dimensionless() -> DimVector: ...
    @staticmethod
    def from_pairs(pairs: list[tuple[str, int]]) -> DimVector: ...
    def is_dimensionless(self) -> bool: ...
    def to_dict(self) -> dict[str, int]: ...
    @property
    def vector(self) -> list[int]: ...
    def __mul__(self, other: DimVector) -> DimVector: ...
    def __truediv__(self, other: DimVector) -> DimVector: ...
    def __pow__(self, exp: int) -> DimVector: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class UnitDefinition:
    def __init__(
        self,
        symbol: str,
        dimension: DimVector,
        converter_kind: str,
        scale: float = ...,
        offset: float = ...,
        factor: float = ...,
        reference: float = ...,
        name: str | None = ...,
        kind: str = ...,
        allow_prefixes: bool = ...,
    ) -> None: ...
    @property
    def symbol(self) -> str: ...
    @property
    def dimension(self) -> DimVector: ...
    @property
    def name(self) -> str | None: ...
    @property
    def allow_prefixes(self) -> bool: ...
    @property
    def kind(self) -> str: ...
    @property
    def is_linear(self) -> bool: ...
    def scale(self) -> float | None: ...
    def offset(self) -> float: ...
    def to_base(self, value: float) -> float: ...
    def from_base(self, value: float) -> float: ...
    def convert_to(self, value: float, target: UnitDefinition) -> float: ...

class Expr:
    @staticmethod
    def number(v: float) -> Expr: ...
    @staticmethod
    def symbol(s: str) -> Expr: ...
    @staticmethod
    def quantity(name: str, unit: RationalUnit) -> Expr: ...
    @staticmethod
    def sin(e: Expr) -> Expr: ...
    @staticmethod
    def cos(e: Expr) -> Expr: ...
    @staticmethod
    def ln(e: Expr) -> Expr: ...
    @staticmethod
    def exp(e: Expr) -> Expr: ...
    def __add__(self, other: Expr) -> Expr: ...
    def __sub__(self, other: Expr) -> Expr: ...
    def __mul__(self, other: Expr) -> Expr: ...
    def __truediv__(self, other: Expr) -> Expr: ...
    def __pow__(self, other: Expr, modulo: Any | None = ...) -> Expr: ...
    def simplify(self) -> Expr: ...
    def factor(self) -> Expr: ...
    def diff(self, var: str, n: int = ...) -> Expr: ...
    def integrate(self, var: str) -> Expr: ...
    def unit(self) -> RationalUnit | None: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

def to_arrow_record_batch(*args: Any, **kwargs: Any) -> Any: ...
def batch_to_si_inplace(buf: Any, factor: float) -> None: ...
def step_euler_inplace(positions: Any, velocities: Any, dt: float) -> None: ...
def batch_scale_and_shift_inplace(
    buf: Any, scale: float, shift: float
) -> None: ...
def parse_unit_expression(expr: str) -> RationalUnit: ...
def eval_dual_number(
    val: float, der: float, op: str
) -> tuple[float, float]: ...
def propagate_hessian_uncertainty(
    f_mean: float, jacobian: Any, hessian: Any, covariance: Any
) -> tuple[float, float]: ...
def convert_units_inplace(
    data: Any, src: UnitDefinition, dst: UnitDefinition
) -> None: ...
def dim_vector_from_dict(pairs: dict[str, int]) -> DimVector: ...

__version__: str
