//! Manifest parsing (`phs.toml`) and package bundle creation (`phs pack`) for `.phs` repositories.
//!
//! Enables Tier 2 versioned packaging of PHS model repositories: verifies syntax across all
//! exported modules, extracts function signatures, checks semver versioning, and generates
//! `.phspkg` distributable bundles.

use std::collections::HashMap;
use std::fs;
use std::path::{Path, PathBuf};

use chrono::Utc;
use physure_core::error::{PhysureError, PhysureResult};
use physure_script::{parse_phs, PhsModule};
use semver::Version;
use serde::{Deserialize, Serialize};

/// Metadata section `[package]` in a `phs.toml` manifest.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct PackageMetadata {
    pub name: String,
    pub version: String,
    #[serde(default)]
    pub authors: Option<Vec<String>>,
    #[serde(default)]
    pub entry: Option<String>,
    #[serde(default)]
    pub description: Option<String>,
    #[serde(default)]
    pub license: Option<String>,
    #[serde(default)]
    pub repository: Option<String>,
}

/// Optional dependencies configuration section `[dependencies]` in `phs.toml`.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Default)]
pub struct DependenciesConfig {
    #[serde(default)]
    pub base_units: Option<String>,
    #[serde(flatten)]
    pub extra: HashMap<String, String>,
}

/// Top-level manifest structure representing a `phs.toml` file.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct Manifest {
    pub package: PackageMetadata,
    #[serde(default)]
    pub dependencies: Option<DependenciesConfig>,
    #[serde(default)]
    pub exports: HashMap<String, String>,
}

/// Summary information for one exported `.phs` module after validation.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct ExportedModuleInfo {
    pub export_name: String,
    pub relative_path: String,
    pub function_names: Vec<String>,
    pub signature_count: usize,
}

/// Validation report generated by [`Manifest::validate`].
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct PackageValidationReport {
    pub package_name: String,
    pub version: String,
    pub entry_file: Option<String>,
    pub modules: Vec<ExportedModuleInfo>,
    pub total_functions: usize,
}

/// A serialized parameter descriptor stored in `.phspkg`.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct SerializedParamInfo {
    pub name: String,
    pub expected_unit: Option<String>,
}

/// A serialized function signature stored in `.phspkg`.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct SerializedFunctionSignature {
    pub name: String,
    pub docstring: Option<String>,
    pub params: Vec<SerializedParamInfo>,
}

/// A bundled `.phs` module stored inside a `.phspkg` package file.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct BundledModule {
    pub export_name: String,
    pub relative_path: String,
    pub source_code: String,
    pub functions: HashMap<String, SerializedFunctionSignature>,
}

/// Self-contained `.phspkg` package bundle structure.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct PhsPackageBundle {
    pub format_version: u32,
    pub manifest: Manifest,
    pub created_at: String,
    pub modules: HashMap<String, BundledModule>,
    pub entry_source: Option<String>,
}

impl Manifest {
    /// Parses a `phs.toml` string into a [`Manifest`].
    pub fn from_str(toml_str: &str) -> PhysureResult<Self> {
        toml::from_str(toml_str)
            .map_err(|e| PhysureError::Generic(format!("Failed to parse phs.toml manifest: {}", e)))
    }

    /// Reads and parses a `phs.toml` file at the specified path.
    pub fn from_file(path: impl AsRef<Path>) -> PhysureResult<Self> {
        let p = path.as_ref();
        let content = fs::read_to_string(p).map_err(|e| {
            PhysureError::Generic(format!(
                "Failed to read manifest file '{}': {}",
                p.display(),
                e
            ))
        })?;
        Self::from_str(&content)
    }

    /// Validates the manifest against files on disk in `base_dir`:
    /// - Checks package name is non-empty and valid.
    /// - Checks version adheres to semantic versioning (semver).
    /// - Verifies that the entry file (if defined) exists and parses without errors.
    /// - Verifies that all exported `.phs` files exist, parse cleanly, and extract valid signatures.
    pub fn validate(&self, base_dir: impl AsRef<Path>) -> PhysureResult<PackageValidationReport> {
        let base = base_dir.as_ref();

        let trimmed_name = self.package.name.trim();
        if trimmed_name.is_empty() {
            return Err(PhysureError::Generic(
                "Package name in phs.toml cannot be empty".into(),
            ));
        }

        // Validate semver
        Version::parse(&self.package.version).map_err(|e| {
            PhysureError::Generic(format!(
                "Invalid semver version '{}' in phs.toml: {}",
                self.package.version, e
            ))
        })?;

        // Validate entry file if specified
        if let Some(ref entry_path_str) = self.package.entry {
            let full_entry = ensure_path_within_base(base, entry_path_str)?;
            if !full_entry.is_file() {
                return Err(PhysureError::Generic(format!(
                    "Package entry file '{}' is not a file in '{}'",
                    entry_path_str,
                    base.display()
                )));
            }
            let entry_code = fs::read_to_string(&full_entry).map_err(|e| {
                PhysureError::Generic(format!(
                    "Cannot read entry file '{}': {}",
                    full_entry.display(),
                    e
                ))
            })?;
            parse_phs(&entry_code).map_err(|e| {
                PhysureError::Generic(format!(
                    "Parse error in entry file '{}': {:?}",
                    full_entry.display(),
                    e
                ))
            })?;
        }

        let mut module_reports = Vec::new();
        let mut total_fns = 0;

        // Sort exports by key for deterministic ordering
        let mut export_keys: Vec<&String> = self.exports.keys().collect();
        export_keys.sort();

        for export_name in export_keys {
            let rel_path = &self.exports[export_name];
            let full_path = ensure_path_within_base(base, rel_path)?;

            if !full_path.is_file() {
                return Err(PhysureError::Generic(format!(
                    "Export '{}' points to non-file '{}' (resolved to '{}')",
                    export_name,
                    rel_path,
                    full_path.display()
                )));
            }

            let source = fs::read_to_string(&full_path).map_err(|e| {
                PhysureError::Generic(format!(
                    "Cannot read export file '{}': {}",
                    full_path.display(),
                    e
                ))
            })?;

            // Ensure source parses
            parse_phs(&source).map_err(|e| {
                PhysureError::Generic(format!(
                    "Parse error in exported module '{}' ('{}'): {:?}",
                    export_name,
                    full_path.display(),
                    e
                ))
            })?;

            // Instantiate PhsModule to extract function signatures
            let module = PhsModule::from_source(export_name, &source).map_err(|e| {
                PhysureError::Generic(format!(
                    "Error loading module '{}' from '{}': {}",
                    export_name,
                    full_path.display(),
                    e
                ))
            })?;

            let mut fn_names: Vec<String> = module.functions.keys().cloned().collect();
            fn_names.sort();
            let sig_count = fn_names.len();
            total_fns += sig_count;

            module_reports.push(ExportedModuleInfo {
                export_name: export_name.clone(),
                relative_path: rel_path.clone(),
                function_names: fn_names,
                signature_count: sig_count,
            });
        }

        Ok(PackageValidationReport {
            package_name: self.package.name.clone(),
            version: self.package.version.clone(),
            entry_file: self.package.entry.clone(),
            modules: module_reports,
            total_functions: total_fns,
        })
    }

    /// Validates the package and creates a self-contained `.phspkg` bundle file.
    pub fn pack(
        &self,
        base_dir: impl AsRef<Path>,
        output_path: Option<impl AsRef<Path>>,
    ) -> PhysureResult<(PathBuf, PackageValidationReport)> {
        let base = base_dir.as_ref();
        let report = self.validate(base)?;

        let mut bundled_modules = HashMap::new();
        for mod_info in &report.modules {
            let full_path = base.join(&mod_info.relative_path);
            let source = fs::read_to_string(&full_path).map_err(|e| {
                PhysureError::Generic(format!("Error reading '{}': {}", full_path.display(), e))
            })?;

            let module = PhsModule::from_source(&mod_info.export_name, &source)?;
            let mut fn_map = HashMap::new();
            for (fn_name, sig) in &module.functions {
                let params = sig
                    .params
                    .iter()
                    .map(|p| SerializedParamInfo {
                        name: p.name.clone(),
                        expected_unit: p.expected_unit.clone(),
                    })
                    .collect();
                fn_map.insert(
                    fn_name.clone(),
                    SerializedFunctionSignature {
                        name: sig.name.clone(),
                        docstring: sig.docstring.clone(),
                        params,
                    },
                );
            }

            bundled_modules.insert(
                mod_info.export_name.clone(),
                BundledModule {
                    export_name: mod_info.export_name.clone(),
                    relative_path: mod_info.relative_path.clone(),
                    source_code: source,
                    functions: fn_map,
                },
            );
        }

        let entry_source = if let Some(ref entry_rel) = self.package.entry {
            let full_entry = base.join(entry_rel);
            Some(fs::read_to_string(&full_entry).map_err(|e| {
                PhysureError::Generic(format!("Error reading entry '{}': {}", full_entry.display(), e))
            })?)
        } else {
            None
        };

        let bundle = PhsPackageBundle {
            format_version: 1,
            manifest: self.clone(),
            created_at: Utc::now().to_rfc3339(),
            modules: bundled_modules,
            entry_source,
        };

        let json_data = serde_json::to_string_pretty(&bundle).map_err(|e| {
            PhysureError::Generic(format!("Failed to serialize package bundle: {}", e))
        })?;

        let target_path = match output_path {
            Some(out) => out.as_ref().to_path_buf(),
            None => {
                let default_name = format!("{}-{}.phspkg", self.package.name, self.package.version);
                base.join(default_name)
            }
        };

        if let Some(parent) = target_path.parent() {
            if !parent.exists() {
                fs::create_dir_all(parent).map_err(|e| {
                    PhysureError::Generic(format!(
                        "Failed to create output directory '{}': {}",
                        parent.display(),
                        e
                    ))
                })?;
            }
        }

        fs::write(&target_path, json_data).map_err(|e| {
            PhysureError::Generic(format!(
                "Failed to write package bundle to '{}': {}",
                target_path.display(),
                e
            ))
        })?;

        Ok((target_path, report))
    }
}

impl PhsPackageBundle {
    /// Loads a `.phspkg` bundle from disk.
    #[allow(dead_code)]
    pub fn from_file(path: impl AsRef<Path>) -> PhysureResult<Self> {
        let p = path.as_ref();
        let content = fs::read_to_string(p).map_err(|e| {
            PhysureError::Generic(format!("Cannot read bundle file '{}': {}", p.display(), e))
        })?;
        let bundle: Self = serde_json::from_str(&content).map_err(|e| {
            PhysureError::Generic(format!(
                "Invalid .phspkg bundle file '{}': {}",
                p.display(),
                e
            ))
        })?;
        if bundle.format_version != 1 {
            return Err(PhysureError::Generic(format!(
                "Unsupported .phspkg format version {} in '{}' (expected version 1)",
                bundle.format_version,
                p.display()
            )));
        }
        Ok(bundle)
    }
}

/// Verifies that `rel_path` resolves to an existing file strictly located inside `base`.
fn ensure_path_within_base(base: &Path, rel_path: &str) -> PhysureResult<std::path::PathBuf> {
    let full_path = base.join(rel_path);
    if !full_path.exists() {
        return Err(PhysureError::Generic(format!(
            "Path '{}' does not exist in '{}'",
            rel_path,
            base.display()
        )));
    }
    let canonical_base = base.canonicalize().map_err(|e| {
        PhysureError::Generic(format!(
            "Cannot resolve base directory '{}': {}",
            base.display(),
            e
        ))
    })?;
    let canonical_target = full_path.canonicalize().map_err(|e| {
        PhysureError::Generic(format!(
            "Cannot resolve target path '{}': {}",
            full_path.display(),
            e
        ))
    })?;
    if !canonical_target.starts_with(&canonical_base) {
        return Err(PhysureError::Generic(format!(
            "Path traversal forbidden: '{}' escapes base directory '{}'",
            rel_path,
            base.display()
        )));
    }
    Ok(full_path)
}

/// CLI runner for `phs pack [dir_or_manifest] [-o <output.phspkg>]`.
pub fn run_pack(args: &[String]) {
    let mut target_dir_or_file = None;
    let mut output_override = None;

    let mut skip_next = false;
    for (i, arg) in args.iter().enumerate().skip(1) {
        if skip_next {
            skip_next = false;
            continue;
        }
        if arg == "pack" {
            continue;
        }
        if arg == "-o" || arg == "--output" {
            if i + 1 < args.len() {
                output_override = Some(args[i + 1].clone());
                skip_next = true;
            }
            continue;
        }
        if target_dir_or_file.is_none() {
            target_dir_or_file = Some(arg.clone());
        }
    }

    let input_path = target_dir_or_file.unwrap_or_else(|| ".".to_string());
    let path = Path::new(&input_path);

    let (manifest_path, base_dir) = if path.is_file() {
        let parent = path.parent().unwrap_or_else(|| Path::new("."));
        (path.to_path_buf(), parent.to_path_buf())
    } else if path.is_dir() {
        let candidate = path.join("phs.toml");
        if !candidate.is_file() {
            eprintln!(
                "Error: manifest file 'phs.toml' not found in directory '{}'",
                path.display()
            );
            std::process::exit(1);
        }
        (candidate, path.to_path_buf())
    } else {
        eprintln!("Error: path '{}' does not exist", path.display());
        std::process::exit(1);
    };

    println!("📦 Reading manifest '{}'...", manifest_path.display());
    let manifest = match Manifest::from_file(&manifest_path) {
        Ok(m) => m,
        Err(e) => {
            eprintln!("Error: {}", e);
            std::process::exit(1);
        }
    };

    println!(
        "🔍 Validating package '{}' v{}...",
        manifest.package.name, manifest.package.version
    );

    let output_path_opt = output_override.map(PathBuf::from);
    match manifest.pack(&base_dir, output_path_opt) {
        Ok((bundle_path, report)) => {
            println!("✓ Validated {} exported module(s):", report.modules.len());
            for m in &report.modules {
                println!(
                    "  - module '{}' ({}): {} function(s) [{}]",
                    m.export_name,
                    m.relative_path,
                    m.signature_count,
                    m.function_names.join(", ")
                );
            }
            if let Some(ref entry) = report.entry_file {
                println!("  - entry file: {}", entry);
            }
            let file_size = fs::metadata(&bundle_path)
                .map(|meta| meta.len())
                .unwrap_or(0);
            println!(
                "
✨ Successfully packed '{}' v{} -> '{}' ({} bytes)",
                manifest.package.name,
                manifest.package.version,
                bundle_path.display(),
                file_size
            );
        }
        Err(e) => {
            eprintln!("Packaging Error: {}", e);
            std::process::exit(1);
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_parse_phs_manifest() {
        let toml = r#"
[package]
name = "fluid-models"
version = "1.0.0"
entry = "main.phs"

[exports]
fluidos = "models/fluidos.phs"
"#;
        let manifest = Manifest::from_str(toml).unwrap();
        assert_eq!(manifest.package.name, "fluid-models");
        assert_eq!(manifest.package.version, "1.0.0");
        assert_eq!(manifest.package.entry.as_deref(), Some("main.phs"));
        assert_eq!(
            manifest.exports.get("fluidos").map(|s| s.as_str()),
            Some("models/fluidos.phs")
        );
    }

    #[test]
    fn test_parse_phs_manifest_with_all_fields() {
        let toml = r#"
[package]
name = "enterprise-fluid-models"
version = "1.2.0"
authors = ["Engineering Core Team <eng@company.com>", "Irvin <irvin@company.com>"]
entry = "models/index.phs"
description = "Industrial fluid dynamics formulas"
license = "MIT"
repository = "https://github.com/company/fluid-models"

[dependencies]
base_units = "si"
fluid_constants = "0.5.0"

[exports]
fluidos = "models/fluidos.phs"
estructuras = "models/estructuras.phs"
"#;
        let manifest = Manifest::from_str(toml).unwrap();
        assert_eq!(manifest.package.name, "enterprise-fluid-models");
        assert_eq!(manifest.package.version, "1.2.0");
        assert_eq!(
            manifest.package.authors,
            Some(vec![
                "Engineering Core Team <eng@company.com>".into(),
                "Irvin <irvin@company.com>".into()
            ])
        );
        assert_eq!(manifest.package.license.as_deref(), Some("MIT"));
        assert_eq!(
            manifest.package.description.as_deref(),
            Some("Industrial fluid dynamics formulas")
        );
        assert_eq!(
            manifest.dependencies.as_ref().unwrap().base_units.as_deref(),
            Some("si")
        );
        assert_eq!(manifest.exports.len(), 2);
    }

    #[test]
    fn test_manifest_validation_and_packing_lifecycle() {
        let temp_dir = std::env::temp_dir().join(format!("phs_pack_test_{}", Utc::now().timestamp_nanos_opt().unwrap_or(0)));
        fs::create_dir_all(temp_dir.join("models")).unwrap();

        let manifest_content = r#"
[package]
name = "demo-pack"
version = "0.1.0"
entry = "main.phs"

[exports]
kinetics = "models/kinetics.phs"
geometry = "models/geometry.phs"
"#;
        fs::write(temp_dir.join("phs.toml"), manifest_content).unwrap();
        fs::write(
            temp_dir.join("main.phs"),
            "fn main() = 42
",
        ).unwrap();
        fs::write(
            temp_dir.join("models/kinetics.phs"),
            "/// Kinetic energy calculation
/// @param m Mass in kg
/// @param v Speed in m/s
fn E_k(m: kg, v: m/s) = 0.5 * m * v^2
",
        ).unwrap();
        fs::write(
            temp_dir.join("models/geometry.phs"),
            "fn circle_area(r: m) = 3.1415926535 * r^2
fn rectangle_area(w: m, h: m) = w * h
",
        ).unwrap();

        let manifest = Manifest::from_file(temp_dir.join("phs.toml")).unwrap();
        let report = manifest.validate(&temp_dir).unwrap();

        assert_eq!(report.package_name, "demo-pack");
        assert_eq!(report.version, "0.1.0");
        assert_eq!(report.modules.len(), 2);
        assert_eq!(report.total_functions, 3);

        // Pack the package
        let bundle_file = temp_dir.join("dist/demo-pack-0.1.0.phspkg");
        let (packed_path, pack_report) = manifest.pack(&temp_dir, Some(&bundle_file)).unwrap();
        assert_eq!(packed_path, bundle_file);
        assert_eq!(pack_report.total_functions, 3);
        assert!(bundle_file.is_file());

        // Load the bundle back
        let bundle = PhsPackageBundle::from_file(&bundle_file).unwrap();
        assert_eq!(bundle.format_version, 1);
        assert_eq!(bundle.manifest.package.name, "demo-pack");
        assert_eq!(bundle.modules.len(), 2);

        let kinetics = &bundle.modules["kinetics"];
        assert_eq!(kinetics.export_name, "kinetics");
        assert!(kinetics.functions.contains_key("E_k"));
        let e_k = &kinetics.functions["E_k"];
        assert_eq!(e_k.params.len(), 2);
        assert_eq!(e_k.params[0].name, "m");
        assert_eq!(e_k.params[0].expected_unit.as_deref(), Some("kg"));

        let _ = fs::remove_dir_all(&temp_dir);
    }

    #[test]
    fn test_manifest_validation_missing_export_fails() {
        let temp_dir = std::env::temp_dir().join(format!("phs_pack_missing_{}", Utc::now().timestamp_nanos_opt().unwrap_or(0)));
        fs::create_dir_all(&temp_dir).unwrap();

        let manifest_content = r#"
[package]
name = "bad-pack"
version = "1.0.0"

[exports]
missing = "does_not_exist.phs"
"#;
        fs::write(temp_dir.join("phs.toml"), manifest_content).unwrap();

        let manifest = Manifest::from_file(temp_dir.join("phs.toml")).unwrap();
        let result = manifest.validate(&temp_dir);
        assert!(result.is_err());
        let err_msg = result.unwrap_err().to_string();
        assert!(err_msg.contains("missing file") || err_msg.contains("does_not_exist.phs"));

        let _ = fs::remove_dir_all(&temp_dir);
    }

    #[test]
    fn test_manifest_validation_syntax_error_in_export_fails() {
        let temp_dir = std::env::temp_dir().join(format!("phs_pack_syntax_{}", Utc::now().timestamp_nanos_opt().unwrap_or(0)));
        fs::create_dir_all(&temp_dir).unwrap();

        let manifest_content = r#"
[package]
name = "syntax-error-pack"
version = "1.0.0"

[exports]
broken = "broken.phs"
"#;
        fs::write(temp_dir.join("phs.toml"), manifest_content).unwrap();
        fs::write(temp_dir.join("broken.phs"), "fn broken( == +++ invalid syntax").unwrap();

        let manifest = Manifest::from_file(temp_dir.join("phs.toml")).unwrap();
        let result = manifest.validate(&temp_dir);
        assert!(result.is_err());
        let err_msg = result.unwrap_err().to_string();
        assert!(err_msg.contains("Parse error"));

        let _ = fs::remove_dir_all(&temp_dir);
    }

    #[test]
    fn test_manifest_invalid_semver_fails() {
        let toml = r#"
[package]
name = "bad-version"
version = "not-a-valid-semver"
"#;
        let manifest = Manifest::from_str(toml).unwrap();
        let result = manifest.validate(".");
        assert!(result.is_err());
        assert!(result.unwrap_err().to_string().contains("Invalid semver"));
    }

    #[test]
    fn test_manifest_path_traversal_is_rejected() {
        let temp_dir = std::env::temp_dir().join(format!("phs_pack_traversal_{}", Utc::now().timestamp_nanos_opt().unwrap_or(0)));
        let sub_dir = temp_dir.join("subpkg");
        fs::create_dir_all(&sub_dir).unwrap();

        // Create an external file outside sub_dir
        fs::write(temp_dir.join("secret.phs"), "fn secret() = 42\n").unwrap();

        let manifest_content = r#"
[package]
name = "traversal-pkg"
version = "1.0.0"

[exports]
hack = "../secret.phs"
"#;
        fs::write(sub_dir.join("phs.toml"), manifest_content).unwrap();

        let manifest = Manifest::from_file(sub_dir.join("phs.toml")).unwrap();
        let result = manifest.validate(&sub_dir);
        assert!(result.is_err());
        let err_msg = result.unwrap_err().to_string();
        assert!(err_msg.contains("Path traversal forbidden"));

        let _ = fs::remove_dir_all(&temp_dir);
    }

    #[test]
    fn test_bundle_unsupported_format_version_fails() {
        let temp_dir = std::env::temp_dir().join(format!("phs_pack_fmt_{}", Utc::now().timestamp_nanos_opt().unwrap_or(0)));
        fs::create_dir_all(&temp_dir).unwrap();

        let bundle_file = temp_dir.join("bad_version.phspkg");
        let bad_json = r#"{
            "format_version": 999,
            "manifest": {
                "package": { "name": "bad", "version": "1.0.0" },
                "exports": {}
            },
            "created_at": "2026-08-28T00:00:00Z",
            "modules": {},
            "entry_source": null
        }"#;
        fs::write(&bundle_file, bad_json).unwrap();

        let result = PhsPackageBundle::from_file(&bundle_file);
        assert!(result.is_err());
        let err = result.unwrap_err().to_string();
        assert!(err.contains("Unsupported .phspkg format version 999"));

        let _ = fs::remove_dir_all(&temp_dir);
    }
}


