# ===============================================
#  Sistema de Unidades Internacional (SI)
# ===============================================

[System]
name = SI
base_units = L:m, M:kg, T:s, I:A, O:K, N:mol, J:cd, A:rad, $:USD

[Units]
celsius = 1.0, 273.15, O, [°C, celsius, centigrade, degC]
fahrenheit = 0.5555555555555556, 255.3722222222222, O, [°F, fahrenheit, degF]

# Explicit Delta Units (Affine Arithmetic Support)
delta_celsius = 1.0, O, [delta_degC, degC_delta]
delta_fahrenheit = 0.5555555555555556, O, [delta_degF, degF_delta]
