import configparser
import os


def generate_units_markdown():
    parser = configparser.ConfigParser()
    parser.optionxform = str
    parser.read(
        "measurekit/infrastructure/config/measurekit.conf", encoding="utf-8"
    )

    md = []
    md.append("# Supported Units, Prefixes, and Constants in MeasureKit\n")
    md.append(
        "This file is automatically generated from the master configuration (`measurekit.conf`).\n"
    )

    # 1. Dimensions
    md.append("## Base & Derived Dimensions\n")
    md.append("| Dimension Name | Base Formula / Symbol |")
    md.append("| --- | --- |")
    for dim_name, formula in parser.items("Dimensions"):
        md.append(f"| {dim_name} | `{formula}` |")
    md.append("\n")

    # 2. Prefixes
    md.append("## Unit Prefixes\n")
    md.append("| Prefix Name | Symbol | Multiplier |")
    md.append("| --- | --- | --- |")
    for pref_name, val in parser.items("Prefixes"):
        parts = [p.strip() for p in val.split(",")]
        sym = parts[0]
        factor = parts[1]
        md.append(f"| {pref_name} | `{sym}` | {factor} |")
    md.append("\n")

    # 3. Units grouped by dimension
    md.append("## Supported Units\n")

    units_by_dim = {}
    for unit_name, val in parser.items("Units"):
        parts = [p.strip() for p in val.split(",")]
        if parts[0] == "Log":
            # e.g. pH = Log, -1, 1.0, 1, noprefix, [pH]
            dim = parts[3]
            scale = f"Log (base {parts[1]}, scale {parts[2]})"
            aliases = parts[4:]
        else:
            try:
                float(parts[1])
                # e.g. celsius = 1.0, 273.15, O, [°C]
                dim = parts[2]
                scale = f"Scale {parts[0]} (Offset {parts[1]})"
                aliases = parts[3:]
            except ValueError:
                # e.g. meter = 1.0, L, [m]
                dim = parts[1]
                scale = f"Scale {parts[0]}"
                aliases = parts[2:]

        aliases_str = ", ".join(aliases).replace("[", "").replace("]", "")

        if dim not in units_by_dim:
            units_by_dim[dim] = []
        units_by_dim[dim].append((unit_name, scale, aliases_str))

    for dim, units in sorted(units_by_dim.items()):
        md.append(f"### Dimension: `{dim}`\n")
        md.append("| Unit Name | Scaling / Converter | Symbols & Aliases |")
        md.append("| --- | --- | --- |")
        for u_name, u_scale, u_aliases in sorted(units):
            md.append(f"| `{u_name}` | {u_scale} | `{u_aliases}` |")
        md.append("\n")

    # 4. Constants
    md.append("## Physical Constants\n")
    md.append("| Constant Name | Value & Unit |")
    md.append("| --- | --- |")
    for const_name, val in parser.items("Constants"):
        md.append(f"| `{const_name}` | `{val}` |")

    os.makedirs("docs", exist_ok=True)
    with open("docs/UNITS.md", "w", encoding="utf-8") as f:
        f.write("\n".join(md))
    print("Successfully generated docs/UNITS.md")


if __name__ == "__main__":
    generate_units_markdown()
