use crate::ast::{AssignmentNode, BinaryOp, Expr, FunctionDefNode, Program, Statement};
use crate::codegen::{snake_to_camel, CodeGenerator, CodegenError};
use std::collections::HashSet;

#[derive(Debug, Clone)]
pub struct JavaTranspiler {
    pub class_name: String,
}

impl Default for JavaTranspiler {
    fn default() -> Self {
        Self {
            class_name: "Main".to_string(),
        }
    }
}

impl JavaTranspiler {
    pub fn new(class_name: &str) -> Self {
        Self {
            class_name: class_name.to_string(),
        }
    }
}

impl CodeGenerator for JavaTranspiler {
    fn generate_program(&self, program: &Program) -> Result<String, CodegenError> {
        let mut out = String::new();
        out.push_str(concat!("// Generated by PhysureScript (PHS) Compiler v", env!("CARGO_PKG_VERSION"), "\n"));
        out.push_str("import com.physure.Quantity;\n");
        out.push_str("import com.physure.PhyEquation;\n");
        out.push_str("import com.physure.PhyFunction;\n");
        out.push_str("import java.util.*;\n\n");
        out.push_str(&format!("public class {} {{\n", self.class_name));

        let mut functions = Vec::new();
        let mut main_stmts = Vec::new();
        let mut main_declared_vars = HashSet::new();
        let mut known_bool_vars: HashSet<String> = HashSet::new();

        for stmt in &program.statements {
            match stmt {
                Statement::FunctionDef(f) => {
                    functions.push(self.generate_function_def_stmt(f)?);
                }
                Statement::Assignment(node) => {
                    main_stmts.push(self.generate_java_assignment(node, "        ", &mut main_declared_vars, &mut known_bool_vars)?);
                    let var_name = snake_to_camel(&node.name);
                    main_stmts.push(format!("        System.out.println(\"{}: \" + {});", node.name, var_name));
                }
                Statement::Expr(expr) => {
                    match super::as_assert_call(expr, &known_bool_vars) {
                        Some(super::AssertShape::Bool { condition }) => {
                            let cond_code = self.generate_expr(condition)?;
                            main_stmts.push(format!("        if (!({})) throw new AssertionError(\"assertion failed\");", cond_code));
                        }
                        Some(super::AssertShape::BoolWithMessage { condition, message }) => {
                            let cond_code = self.generate_expr(condition)?;
                            let msg_code = self.generate_expr(message)?;
                            main_stmts.push(format!("        if (!({})) throw new AssertionError({});", cond_code, msg_code));
                        }
                        Some(super::AssertShape::Quantities { kind, actual, expected }) => {
                            let a_code = self.generate_expr(actual)?;
                            let b_code = self.generate_expr(expected)?;
                            let method = if kind == "assert" { "physAssert" } else { "physExactAssert" };
                            main_stmts.push(format!("        {}.{}({});", a_code, method, b_code));
                        }
                        None => {
                            let val = self.generate_expr(expr)?;
                            main_stmts.push(format!("        System.out.println({});", val));
                        }
                    }
                }
                Statement::While { .. } => {
                    main_stmts.push(format!("        {}", self.generate_statement(stmt, &mut main_declared_vars, &mut known_bool_vars)?));
                }
                _ => {}
            }
        }

        for func in functions {
            out.push_str(&func);
            out.push('\n');
        }

        if !main_stmts.is_empty() {
            out.push_str("    public static void main(String[] args) {\n");
            out.push_str(&main_stmts.join("\n"));
            out.push_str("\n    }\n");
        }

        out.push_str("}\n");
        Ok(out)
    }
}

impl JavaTranspiler {
    /// Emits one Java local-variable declaration or reassignment, tracking `known_bool_vars` so a
    /// later use of this name (another assignment, or an `assert` call) knows whether it holds a
    /// `boolean`. `indent` is the caller's own per-line prefix.
    fn generate_java_assignment(
        &self,
        node: &AssignmentNode,
        indent: &str,
        declared_vars: &mut HashSet<String>,
        known_bool_vars: &mut HashSet<String>,
    ) -> Result<String, CodegenError> {
        let val = self.generate_expr(&node.value)?;
        let var_name = snake_to_camel(&node.name);
        let is_reassign = declared_vars.contains(&var_name);
        let is_bool_now = super::is_definitely_bool(&node.value, known_bool_vars);

        if is_reassign && known_bool_vars.contains(&var_name) && !is_bool_now {
            return Err(CodegenError::Generic(format!(
                "'{}' was previously assigned a Bool expression and cannot be reassigned to a non-Bool value in Java codegen",
                node.name
            )));
        }
        if !is_reassign {
            declared_vars.insert(var_name.clone());
        }
        if is_bool_now {
            known_bool_vars.insert(var_name.clone());
        } else {
            known_bool_vars.remove(&var_name);
        }

        if is_reassign {
            return Ok(format!("{}{} = {};", indent, var_name, val));
        }
        if is_bool_now {
            return Ok(format!("{}boolean {} = {};", indent, var_name, val));
        }
        let literal = match &node.value {
            Expr::Str(text) => Some(text.as_str()),
            _ => None,
        };
        let is_equation = literal.is_some_and(|t| t.contains('=') && !t.contains('{'));
        if literal.is_some() && !is_equation {
            Ok(format!("{}String {} = {};", indent, var_name, val))
        } else if (val.starts_with('"') && val.contains('=')) || val.contains(".solve(") || val.starts_with("PhyEquation") {
            Ok(format!("{}PhyEquation {} = {};", indent, var_name, if val.starts_with('"') { format!("PhyEquation.of({})", val) } else { val }))
        } else if val.starts_with("PhyFunction") {
            Ok(format!("{}PhyFunction {} = {};", indent, var_name, val))
        } else {
            Ok(format!("{}Quantity {} = {};", indent, var_name, val))
        }
    }

    fn generate_function_def_stmt(&self, f: &FunctionDefNode) -> Result<String, CodegenError> {
        let mut out = String::new();
        out.push_str(&format!("    public static Quantity {}(", snake_to_camel(&f.name)));
        let params: Vec<String> = f.params.iter().map(|p| format!("Quantity {}", snake_to_camel(p))).collect();
        out.push_str(&params.join(", "));
        out.push_str(") {\n");
        let mut fn_declared_vars = HashSet::new();
        let mut fn_known_bools: HashSet<String> = HashSet::new();
        for p in &f.params {
            fn_declared_vars.insert(snake_to_camel(p));
        }
        let last_idx = f.body_stmts.len().saturating_sub(1);
        for (i, stmt) in f.body_stmts.iter().enumerate() {
            if i == last_idx {
                if let Statement::Expr(ref e) = stmt {
                    out.push_str(&format!("        return {};\n", self.generate_expr(e)?));
                } else {
                    out.push_str(&format!("        {};\n", self.generate_statement(stmt, &mut fn_declared_vars, &mut fn_known_bools)?));
                }
            } else {
                out.push_str(&format!("        {};\n", self.generate_statement(stmt, &mut fn_declared_vars, &mut fn_known_bools)?));
            }
        }
        out.push_str("    }\n");
        Ok(out)
    }

    fn generate_statement(&self, stmt: &Statement, declared_vars: &mut HashSet<String>, known_bool_vars: &mut HashSet<String>) -> Result<String, CodegenError> {
        match stmt {
            Statement::FunctionDef(f) => self.generate_function_def_stmt(f),
            Statement::Assignment(node) => self.generate_java_assignment(node, "", declared_vars, known_bool_vars),
            Statement::Expr(expr) => {
                match super::as_assert_call(expr, known_bool_vars) {
                    Some(super::AssertShape::Bool { condition }) => {
                        Ok(format!("if (!({})) throw new AssertionError(\"assertion failed\")", self.generate_expr(condition)?))
                    }
                    Some(super::AssertShape::BoolWithMessage { condition, message }) => {
                        Ok(format!("if (!({})) throw new AssertionError({})", self.generate_expr(condition)?, self.generate_expr(message)?))
                    }
                    Some(super::AssertShape::Quantities { kind, actual, expected }) => {
                        let a_code = self.generate_expr(actual)?;
                        let b_code = self.generate_expr(expected)?;
                        let method = if kind == "assert" { "physAssert" } else { "physExactAssert" };
                        Ok(format!("{}.{}({})", a_code, method, b_code))
                    }
                    None => self.generate_expr(expr),
                }
            }
            Statement::Return(expr) => Ok(format!("return {}", self.generate_expr(expr)?)),
            Statement::GuardReturn { cond, value } => {
                Ok(format!("if ({}) {{ return {}; }}", self.generate_expr(cond)?, self.generate_expr(value)?))
            }
            Statement::While { cond, body, .. } => {
                let cond_str = self.generate_expr(cond)?;
                let mut lines = Vec::new();
                for s in body {
                    let stmt_code = self.generate_statement(s, declared_vars, known_bool_vars)?;
                    if !stmt_code.is_empty() {
                        let stmt_with_semi = if stmt_code.ends_with(';') || stmt_code.ends_with('}') {
                            stmt_code
                        } else {
                            format!("{};", stmt_code)
                        };
                        for line in stmt_with_semi.lines() {
                            lines.push(format!("  {}", line));
                        }
                    }
                }
                Ok(format!("while ({}) {{\n{}\n}}", cond_str, lines.join("\n")))
            }
            _ => Ok(String::new()),
        }
    }

    fn generate_expr(&self, expr: &Expr) -> Result<String, CodegenError> {
        match expr {
            Expr::Str(text) => {
                // Java has no interpolating literal, but `+` concatenates and calls
                // toString() on each operand, which is what the interpreter does too.
                let parts = super::split_interpolated(text);
                let mut pieces = Vec::new();
                for (i, part) in parts.iter().enumerate() {
                    match part {
                        super::StrPart::Text(t) => pieces.push(format!("{:?}", t)),
                        super::StrPart::Expr(e) => {
                            // The chain has to start from a String, or `+` between two
                            // numbers would add them instead of concatenating.
                            if i == 0 {
                                pieces.push("\"\"".to_string());
                            }
                            pieces.push(self.generate_expr(e)?);
                        }
                    }
                }
                Ok(if pieces.len() == 1 { pieces.remove(0) } else { format!("({})", pieces.join(" + ")) })
            }
            Expr::Bool(b) => Ok(if *b { "true" } else { "false" }.to_string()),
            Expr::Identifier(id) => Ok(snake_to_camel(id)),
            Expr::Quantity(q) => {
                if let Some(reason) = q.asymmetric_refusal() {
                    return Err(CodegenError::Generic(reason));
                }
                let mut args = vec![format!("{:?}", q.magnitude)];
                
                let is_with_unc = q.uncertainty.is_some();
                if let Some(unc) = q.uncertainty {
                    args.push(format!("{:?}", unc));
                }
                if let Some(ref unit) = q.unit {
                    args.push(format!("\"{}\"", unit));
                }

                if is_with_unc {
                    Ok(format!("Quantity.withUncertainty({})", args.join(", ")))
                } else if q.unit.is_some() {
                    Ok(format!("Quantity.of({})", args.join(", ")))
                } else {
                    Ok(format!("Quantity.of({})", args.join(", ")))
                }
            }
            Expr::BinaryOp { op, left, right } => {
                let l = self.generate_expr(left)?;
                if *op == BinaryOp::Convert {
                    let unit_str = super::expr_to_unit_string(right);
                    Ok(format!("{}.convertTo(\"{}\")", l, unit_str))
                } else if *op == BinaryOp::Pow {
                    if let Expr::Quantity(q) = &**right {
                        return Ok(format!("{}.pow({})", l, q.magnitude));
                    }
                    let r = self.generate_expr(right)?;
                    Ok(format!("{}.pow({}.getValue())", l, r))
                } else {
                    let r = self.generate_expr(right)?;
                    let method = match op {
                        BinaryOp::Add => "add",
                        BinaryOp::Sub => "subtract",
                        BinaryOp::Mul => "multiply",
                        BinaryOp::Div => "divide",
                        BinaryOp::Pow => unreachable!(),
                        BinaryOp::Convert => unreachable!(),
                        BinaryOp::Range => return Err(super::range_is_not_transpilable()),
                    };
                    Ok(format!("{}.{}({})", l, method, r))
                }
            }
            Expr::FunctionCall { name, args, kwargs } => {
                if let Some((op_sym, l, r)) = super::as_comparison_op(expr) {
                    let l_str = self.generate_expr(l)?;
                    let r_str = self.generate_expr(r)?;
                    return Ok(match op_sym {
                        ">" => format!("{}.greaterThan({})", l_str, r_str),
                        "<" => format!("{}.lessThan({})", l_str, r_str),
                        ">=" => format!("!{}.lessThan({})", l_str, r_str),
                        "<=" => format!("!{}.greaterThan({})", l_str, r_str),
                        "==" => format!("{}.equals({})", l_str, r_str),
                        "!=" => format!("!{}.equals({})", l_str, r_str),
                        _ => unreachable!(),
                    });
                }
                if let Some(logical) = super::as_logical_op(expr) {
                    return Ok(match logical {
                        super::LogicalOp::Not(x) => format!("(!{})", self.generate_expr(x)?),
                        super::LogicalOp::And(l, r) => format!("({} && {})", self.generate_expr(l)?, self.generate_expr(r)?),
                        super::LogicalOp::Or(l, r) => format!("({} || {})", self.generate_expr(l)?, self.generate_expr(r)?),
                    });
                }
                if !kwargs.is_empty() {
                    return Err(CodegenError::Generic(format!(
                        "Named arguments are not supported in Java codegen (call to '{}')",
                        name
                    )));
                }
                if (name == "assert" || name == "exact_assert") && matches!(args.len(), 1 | 2) {
                    return Err(CodegenError::Generic(format!(
                        "'{}' can only be used as a standalone statement, not nested inside an expression",
                        name
                    )));
                }
                let mut arg_strs = Vec::new();
                for a in args {
                    arg_strs.push(self.generate_expr(a)?);
                }
                Ok(format!("{}({})", snake_to_camel(name), arg_strs.join(", ")))
            }
            Expr::ForExpr { var, iterable, body } => {
                let it_str = self.generate_expr(iterable)?;
                let var_str = snake_to_camel(var);
                let body_str = self.generate_expr(body)?;
                Ok(format!("({}).stream().map({} -> {}).collect(java.util.stream.Collectors.toList())", it_str, var_str, body_str))
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ast::{FunctionDefNode, QuantityNode};

    #[test]
    fn test_transpile_function_def() {
        let transpiler = JavaTranspiler::default();
        let func = Statement::FunctionDef(FunctionDefNode {
            name: "kinetic_energy".to_string(),
            params: vec!["m".to_string(), "v".to_string()],
            param_units: vec![None, None],
            body_stmts: vec![Statement::Expr(Expr::BinaryOp {
                op: BinaryOp::Mul,
                left: Box::new(Expr::Identifier("m".to_string())),
                right: Box::new(Expr::Identifier("v".to_string())),
            })],
            body_lines: vec![],
            decorators: Vec::new(),
            doc: None,
        });
        
        let result = transpiler.generate_statement(&func, &mut HashSet::new(), &mut HashSet::new()).unwrap();
        assert!(result.contains("public static Quantity kineticEnergy(Quantity m, Quantity v)"));
        assert!(result.contains("return m.multiply(v);"));
    }

    #[test]
    fn test_transpile_quantity_with_uncertainty() {
        let transpiler = JavaTranspiler::default();
        let q = Expr::Quantity(QuantityNode {
            magnitude: 75.0,
            uncertainty: Some(0.5),
            uncertainty_lower: None,
            is_sigma: false,
            unit: Some("kg".to_string()),
        });
        let result = transpiler.generate_expr(&q).unwrap();
        assert_eq!(result, "Quantity.withUncertainty(75.0, 0.5, \"kg\")");
    }

    #[test]
    fn transpiles_bool_literals_java() {
        let tp = JavaTranspiler::default();
        assert_eq!(tp.generate_expr(&Expr::Bool(true)).unwrap(), "true");
        assert_eq!(tp.generate_expr(&Expr::Bool(false)).unwrap(), "false");
    }

    #[test]
    fn transpiles_assert_call_to_phys_assert_call() {
        let transpiler = JavaTranspiler::default();
        let program = crate::parser::parse_phs("assert(1.0 km, 1000.0 m)").unwrap();
        let code = transpiler.generate_program(&program).unwrap();
        assert!(code.contains(".physAssert("), "expected physAssert call:\n{code}");
    }

    #[test]
    fn transpiles_exact_assert_call_to_phys_exact_assert_call() {
        let transpiler = JavaTranspiler::default();
        let program = crate::parser::parse_phs("exact_assert(5.0 m, 5.0 m)").unwrap();
        let code = transpiler.generate_program(&program).unwrap();
        assert!(code.contains(".physExactAssert("), "expected physExactAssert call:\n{code}");
    }

    #[test]
    fn rejects_assert_used_as_a_nested_expression_java() {
        let transpiler = JavaTranspiler::default();
        let program = crate::parser::parse_phs("x = assert(1.0 m, 1.0 m)").unwrap();
        assert!(transpiler.generate_program(&program).is_err());
    }

    #[test]
    fn test_transpile_for_expr_and_while_stmt_java() {
        let tp = JavaTranspiler::default();
        let for_expr = Expr::ForExpr {
            var: "x".to_string(),
            iterable: Box::new(Expr::Identifier("items".to_string())),
            body: Box::new(Expr::Identifier("x".to_string())),
        };
        let code_for = tp.generate_expr(&for_expr).unwrap();
        assert_eq!(code_for, "(items).stream().map(x -> x).collect(java.util.stream.Collectors.toList())");

        let while_stmt = Statement::While {
            cond: Expr::Identifier("flag".to_string()),
            body: vec![Statement::Return(Expr::Identifier("x".to_string()))],
            body_lines: vec![],
        };
        let code_while = tp.generate_statement(&while_stmt, &mut HashSet::new(), &mut HashSet::new()).unwrap();
        assert_eq!(code_while, "while (flag) {\n  return x;\n}");
    }

    #[test]
    fn test_java_reassignment_in_while_loop() {
        let tp = JavaTranspiler::default();
        let program = crate::parser::parse_phs("i = 0\nwhile i < 5 {\n  i = i + 1\n}").unwrap();
        let code = tp.generate_program(&program).unwrap();
        assert!(code.contains("Quantity i = Quantity.of(0"));
        assert!(code.contains("i = i.add("));
        assert!(!code.contains("Quantity i = i.add"));
    }

    #[test]
    fn transpiles_logical_operators_java() {
        let tp = JavaTranspiler::default();
        let and_expr = Expr::FunctionCall { name: "op_and".to_string(), args: vec![Expr::Bool(true), Expr::Bool(false)], kwargs: vec![] };
        assert_eq!(tp.generate_expr(&and_expr).unwrap(), "(true && false)");
    }

    #[test]
    fn named_bool_assignment_gets_an_explicit_boolean_type_java() {
        let tp = JavaTranspiler::default();
        let program = crate::parser::parse_phs("ok = 1.0 m > 0.0 m\nassert(ok, \"should hold\")").unwrap();
        let code = tp.generate_program(&program).unwrap();
        assert!(code.contains("boolean ok = "), "expected an explicit boolean declaration:\n{code}");
        assert!(code.contains("throw new AssertionError(\"should hold\")"), "{code}");
    }

    #[test]
    fn reassigning_a_known_bool_variable_to_a_quantity_is_a_codegen_error_java() {
        let tp = JavaTranspiler::default();
        let program = crate::parser::parse_phs("ok = 1.0 m > 0.0 m\nok = 5.0 m\n").unwrap();
        assert!(tp.generate_program(&program).is_err());
    }

    #[test]
    fn rejects_one_argument_assert_nested_in_an_expression_java() {
        let tp = JavaTranspiler::default();
        let program = crate::parser::parse_phs("x = assert(1.0 m > 0.0 m)").unwrap();
        assert!(tp.generate_program(&program).is_err());
    }
}
