use physure_core::error::PhysureResult;
use crate::ast::{BinaryOp, Expr, Statement, UnaryOp};
use super::CodeGenerator;
use std::collections::HashSet;

pub struct JavaCodeGenerator {
    known_vars: HashSet<String>,
}

impl JavaCodeGenerator {
    pub fn new() -> Self {
        Self {
            known_vars: HashSet::new(),
        }
    }
}

impl CodeGenerator for JavaCodeGenerator {
    fn generate_program(&mut self, statements: &[Statement]) -> PhysureResult<String> {
        let mut out = String::new();
        out.push_str("// Generated by Physure Native AST Codegen\n");
        out.push_str("import com.physure.Quantity;\n");
        out.push_str("import com.physure.QuantityVector;\n");
        out.push_str("import com.physure.PhyFunction;\n\n");
        out.push_str("public class PhysureGenerated {\n");
        out.push_str("    public static void main(String[] args) throws Exception {\n");

        for stmt in statements {
            let stmt_code = self.generate_statement(stmt)?;
            if !stmt_code.is_empty() {
                out.push_str(&format!("        {}\n", stmt_code));
            }
        }

        out.push_str("    }\n");
        out.push_str("}\n");
        Ok(out)
    }

    fn generate_statement(&mut self, stmt: &Statement) -> PhysureResult<String> {
        match stmt {
            Statement::Assign { name, expr } => {
                let expr_str = self.generate_expr(expr)?;
                let decl = if self.known_vars.contains(name) {
                    format!("{} = ", name)
                } else {
                    self.known_vars.insert(name.clone());
                    format!("Quantity {} = ", name)
                };
                Ok(format!("{}{};", decl, expr_str))
            }
            Statement::Query { expr } => {
                let expr_str = self.generate_expr(expr)?;
                Ok(format!("System.out.println({});", expr_str))
            }
            Statement::AssignAndQuery { name, expr } => {
                let expr_str = self.generate_expr(expr)?;
                let decl = if self.known_vars.contains(name) {
                    format!("{} = ", name)
                } else {
                    self.known_vars.insert(name.clone());
                    format!("Quantity {} = ", name)
                };
                Ok(format!("{}{};\n        System.out.println({});", decl, expr_str, name))
            }
            Statement::Assert { left, right, op: _ } => {
                let l_str = self.generate_expr(left)?;
                let r_str = self.generate_expr(right)?;
                Ok(format!("System.out.println(Math.abs({}.getMean() - {}.getMean()) <= 0.5);", l_str, r_str))
            }
            Statement::FnDef { name, params: _, body: _ } => {
                Ok(format!("PhyFunction {} = PhyFunction.of(\"{}\");", name, name))
            }
            Statement::DisplayText(text) => {
                let escaped = text.replace('\\', "\\\\").replace('"', "\\\"").replace('\n', "\\n");
                Ok(format!("System.out.println(\"{}\");", escaped))
            }
            Statement::ExprStmt(expr) => {
                let expr_str = self.generate_expr(expr)?;
                Ok(format!("System.out.println({});", expr_str))
            }
        }
    }

    fn generate_expr(&mut self, expr: &Expr) -> PhysureResult<String> {
        match expr {
            Expr::Number(n) => Ok(format!("new Quantity({:?}, \"\")", n)),
            Expr::Ident(name) => Ok(name.clone()),
            Expr::StringLiteral(s) => Ok(format!("\"{}\"", s)),
            Expr::Unary { op, expr } => {
                let inner = self.generate_expr(expr)?;
                match op {
                    UnaryOp::Neg => Ok(format!("{}.multiply(new Quantity(-1.0, \"\"))", inner)),
                    UnaryOp::Sqrt => Ok(format!("{}.sqrt()", inner)),
                }
            }
            Expr::Binary { op, left, right } => {
                let l_str = self.generate_expr(left)?;
                let r_str = self.generate_expr(right)?;
                match op {
                    BinaryOp::Add => Ok(format!("{}.add({})", l_str, r_str)),
                    BinaryOp::Sub => Ok(format!("{}.subtract({})", l_str, r_str)),
                    BinaryOp::Mul => Ok(format!("{}.multiply({})", l_str, r_str)),
                    BinaryOp::Div => Ok(format!("{}.divide({})", l_str, r_str)),
                    BinaryOp::Pow => Ok(format!("{}.pow({}.getMean())", l_str, r_str)),
                    _ => Ok(format!("{}.add({})", l_str, r_str)),
                }
            }
            Expr::ImplicitMul { left, right } => {
                if let Expr::Number(n) = **left {
                    if let Expr::Ident(ref u) = **right {
                        return Ok(format!("new Quantity({:?}, \"{}\")", n, u));
                    }
                }
                let l_str = self.generate_expr(left)?;
                let r_str = self.generate_expr(right)?;
                Ok(format!("{}.multiply({})", l_str, r_str))
            }
            Expr::Call { name, args } => {
                let formatted_args = args.iter().map(|a| self.generate_expr(a)).collect::<PhysureResult<Vec<_>>>()?.join(", ");
                Ok(format!("{}.apply({})", name, formatted_args))
            }
            Expr::Convert { expr, target_unit } => {
                let inner = self.generate_expr(expr)?;
                Ok(format!("{}.to(\"{}\")", inner, target_unit))
            }
            Expr::FormatSig { expr, spec: _ } => self.generate_expr(expr),
            _ => Ok(format!("new Quantity(0.0, \"\")")),
        }
    }
}
