use crate::ast::{BinaryOp, Expr, Program, Statement};
use crate::codegen::{CodeGenerator, CodegenError};

#[derive(Debug, Clone)]
pub struct JavaTranspiler {
    pub class_name: String,
}

impl Default for JavaTranspiler {
    fn default() -> Self {
        Self {
            class_name: "Main".to_string(),
        }
    }
}

impl JavaTranspiler {
    pub fn new(class_name: &str) -> Self {
        Self {
            class_name: class_name.to_string(),
        }
    }
}

impl CodeGenerator for JavaTranspiler {
    fn generate_program(&self, program: &Program) -> Result<String, CodegenError> {
        let mut out = String::new();
        out.push_str(concat!("// Generated by PhysureScript (PHS) Compiler v", env!("CARGO_PKG_VERSION"), "\n"));
        out.push_str("import com.physure.Quantity;\n");
        out.push_str("import com.physure.PhyEquation;\n");
        out.push_str("import com.physure.PhyFunction;\n");
        out.push_str("import java.util.*;\n\n");
        out.push_str(&format!("public class {} {{\n", self.class_name));

        let mut functions = Vec::new();
        let mut main_stmts = Vec::new();

        for stmt in &program.statements {
            match stmt {
                Statement::FunctionDef(f) => {
                    functions.push(self.generate_function_def_stmt(f)?);
                }
                Statement::Assignment(node) => {
                    let val = self.generate_expr(&node.value)?;
                    let var_name = snake_to_camel(&node.name);
                    // Java is typed, so a string-valued assignment has to be declared as
                    // one; it used to be declared `Quantity` and refuse to compile. An
                    // uninterpolated literal spelling an equation stays a PhyEquation.
                    let literal = match &node.value {
                        Expr::Str(text) => Some(text.as_str()),
                        _ => None,
                    };
                    let is_equation = literal.is_some_and(|t| t.contains('=') && !t.contains('{'));
                    if literal.is_some() && !is_equation {
                        main_stmts.push(format!("        String {} = {};", var_name, val));
                    } else if (val.starts_with('"') && val.contains('=')) || val.contains(".solve(") || val.starts_with("PhyEquation") {
                        main_stmts.push(format!("        PhyEquation {} = {};", var_name, if val.starts_with('"') { format!("PhyEquation.of({})", val) } else { val }));
                    } else if val.starts_with("PhyFunction") {
                        main_stmts.push(format!("        PhyFunction {} = {};", var_name, val));
                    } else {
                        main_stmts.push(format!("        Quantity {} = {};", var_name, val));
                    }
                    main_stmts.push(format!("        System.out.println(\"{}: \" + {});", node.name, var_name));
                }
                Statement::Expr(expr) => {
                    let val = self.generate_expr(expr)?;
                    main_stmts.push(format!("        System.out.println({});", val));
                }
                _ => {}
            }
        }

        for func in functions {
            out.push_str(&func);
            out.push('\n');
        }

        if !main_stmts.is_empty() {
            out.push_str("    public static void main(String[] args) {\n");
            out.push_str(&main_stmts.join("\n"));
            out.push_str("\n    }\n");
        }

        out.push_str("}\n");
        Ok(out)
    }
}

fn snake_to_camel(s: &str) -> String {
    let mut result = String::new();
    let mut capitalize_next = false;
    for (i, c) in s.chars().enumerate() {
        if c == '_' {
            capitalize_next = true;
        } else {
            if capitalize_next && i > 0 {
                result.push(c.to_ascii_uppercase());
            } else {
                result.push(c);
            }
            capitalize_next = false;
        }
    }
    result
}

impl JavaTranspiler {
    fn generate_function_def_stmt(&self, f: &crate::ast::FunctionDefNode) -> Result<String, CodegenError> {
        let mut out = String::new();
        out.push_str(&format!("    public static Quantity {}(", snake_to_camel(&f.name)));
        let params: Vec<String> = f.params.iter().map(|p| format!("Quantity {}", snake_to_camel(p))).collect();
        out.push_str(&params.join(", "));
        out.push_str(") {\n");
        let last_idx = f.body_stmts.len().saturating_sub(1);
        for (i, stmt) in f.body_stmts.iter().enumerate() {
            if i == last_idx {
                if let Statement::Expr(ref e) = stmt {
                    out.push_str(&format!("        return {};\n", self.generate_expr(e)?));
                } else {
                    out.push_str(&format!("        {};\n", self.generate_statement(stmt)?));
                }
            } else {
                out.push_str(&format!("        {};\n", self.generate_statement(stmt)?));
            }
        }
        out.push_str("    }\n");
        Ok(out)
    }

    fn generate_statement(&self, stmt: &Statement) -> Result<String, CodegenError> {
        match stmt {
            Statement::FunctionDef(f) => self.generate_function_def_stmt(f),
            Statement::Return(expr) => Ok(format!("return {}", self.generate_expr(expr)?)),
            Statement::GuardReturn { cond, value } => {
                Ok(format!("if ({}) {{ return {}; }}", self.generate_expr(cond)?, self.generate_expr(value)?))
            }
            _ => Ok(String::new()),
        }
    }

    fn generate_expr(&self, expr: &Expr) -> Result<String, CodegenError> {
        match expr {
            Expr::Str(text) => {
                // Java has no interpolating literal, but `+` concatenates and calls
                // toString() on each operand, which is what the interpreter does too.
                let parts = super::split_interpolated(text);
                let mut pieces = Vec::new();
                for (i, part) in parts.iter().enumerate() {
                    match part {
                        super::StrPart::Text(t) => pieces.push(format!("{:?}", t)),
                        super::StrPart::Expr(e) => {
                            // The chain has to start from a String, or `+` between two
                            // numbers would add them instead of concatenating.
                            if i == 0 {
                                pieces.push("\"\"".to_string());
                            }
                            pieces.push(self.generate_expr(e)?);
                        }
                    }
                }
                Ok(if pieces.len() == 1 { pieces.remove(0) } else { format!("({})", pieces.join(" + ")) })
            }
            Expr::Identifier(id) => Ok(snake_to_camel(id)),
            Expr::Quantity(q) => {
                if let Some(reason) = q.asymmetric_refusal() {
                    return Err(CodegenError::Generic(reason));
                }
                let mut args = vec![format!("{:?}", q.magnitude)];
                
                let is_with_unc = q.uncertainty.is_some();
                if let Some(unc) = q.uncertainty {
                    args.push(format!("{:?}", unc));
                }
                if let Some(ref unit) = q.unit {
                    args.push(format!("\"{}\"", unit));
                }

                if is_with_unc {
                    Ok(format!("Quantity.withUncertainty({})", args.join(", ")))
                } else if q.unit.is_some() {
                    Ok(format!("Quantity.of({})", args.join(", ")))
                } else {
                    Ok(format!("Quantity.of({})", args.join(", ")))
                }
            }
            Expr::BinaryOp { op, left, right } => {
                let l = self.generate_expr(left)?;
                if *op == BinaryOp::Convert {
                    let unit_str = super::expr_to_unit_string(right);
                    Ok(format!("{}.convertTo(\"{}\")", l, unit_str))
                } else if *op == BinaryOp::Pow {
                    if let Expr::Quantity(q) = &**right {
                        return Ok(format!("{}.pow({})", l, q.magnitude));
                    }
                    let r = self.generate_expr(right)?;
                    Ok(format!("{}.pow({}.getValue())", l, r))
                } else {
                    let r = self.generate_expr(right)?;
                    let method = match op {
                        BinaryOp::Add => "add",
                        BinaryOp::Sub => "subtract",
                        BinaryOp::Mul => "multiply",
                        BinaryOp::Div => "divide",
                        BinaryOp::Pow => unreachable!(),
                        BinaryOp::Convert => unreachable!(),
                        BinaryOp::Range => return Err(super::range_is_not_transpilable()),
                    };
                    Ok(format!("{}.{}({})", l, method, r))
                }
            }
            Expr::FunctionCall { name, args, kwargs } => {
                if !kwargs.is_empty() {
                    return Err(CodegenError::Generic(format!(
                        "Named arguments are not supported in Java codegen (call to '{}')",
                        name
                    )));
                }
                let mut arg_strs = Vec::new();
                for a in args {
                    arg_strs.push(self.generate_expr(a)?);
                }
                Ok(format!("{}({})", snake_to_camel(name), arg_strs.join(", ")))
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ast::{FunctionDefNode, QuantityNode};

    #[test]
    fn test_transpile_function_def() {
        let transpiler = JavaTranspiler::default();
        let func = Statement::FunctionDef(FunctionDefNode {
            name: "kinetic_energy".to_string(),
            params: vec!["m".to_string(), "v".to_string()],
            param_units: vec![None, None],
            body_stmts: vec![Statement::Expr(Expr::BinaryOp {
                op: BinaryOp::Mul,
                left: Box::new(Expr::Identifier("m".to_string())),
                right: Box::new(Expr::Identifier("v".to_string())),
            })],
            decorators: Vec::new(),
        });
        
        let result = transpiler.generate_statement(&func).unwrap();
        assert!(result.contains("public static Quantity kineticEnergy(Quantity m, Quantity v)"));
        assert!(result.contains("return m.multiply(v);"));
    }

    #[test]
    fn test_transpile_quantity_with_uncertainty() {
        let transpiler = JavaTranspiler::default();
        let q = Expr::Quantity(QuantityNode {
            magnitude: 75.0,
            uncertainty: Some(0.5),
            uncertainty_lower: None,
            is_sigma: false,
            unit: Some("kg".to_string()),
        });
        let result = transpiler.generate_expr(&q).unwrap();
        assert_eq!(result, "Quantity.withUncertainty(75.0, 0.5, \"kg\")");
    }
}
