use crate::ast::{BinaryOp, Expr, FunctionDefNode, Program, Statement};
use crate::codegen::{snake_to_camel, CodeGenerator, CodegenError};
use std::collections::HashSet;

#[derive(Debug, Clone, Default)]
pub struct JsTranspiler {
    /// false = plain JavaScript, true = TypeScript (adds type annotations).
    pub typed: bool,
}

/// Names assigned inside a `while` body anywhere in the program: a top-level variable of
/// one of these names needs `let` rather than `const`, since a later loop iteration
/// reassigns it (and JS's block scoping means a *nested* `let` there would shadow instead
/// of mutating).
fn names_reassigned_in_loops(stmts: &[Statement]) -> HashSet<String> {
    let mut names = HashSet::new();
    for stmt in stmts {
        if let Statement::While { body, .. } = stmt {
            for s in body {
                if let Statement::Assignment(node) = s {
                    names.insert(snake_to_camel(&node.name));
                }
            }
            names.extend(names_reassigned_in_loops(body));
        }
    }
    names
}

impl CodeGenerator for JsTranspiler {
    fn generate_program(&self, program: &Program) -> Result<String, CodegenError> {
        let mut out = String::new();
        out.push_str(concat!("// Generated by PhysureScript (PHS) Compiler v", env!("CARGO_PKG_VERSION"), "\n"));
        out.push_str("import { Quantity } from \"physure\";\n\n");

        let mut functions = Vec::new();
        let mut main_stmts = Vec::new();
        let mut main_declared_vars = HashSet::new();
        let reassigned = names_reassigned_in_loops(&program.statements);

        for stmt in &program.statements {
            match stmt {
                Statement::FunctionDef(f) => {
                    functions.push(self.generate_function_def_stmt(f)?);
                }
                Statement::Assignment(node) => {
                    let val = self.generate_expr(&node.value)?;
                    let var_name = snake_to_camel(&node.name);
                    let is_str_literal = matches!(&node.value, Expr::Str(_));
                    main_declared_vars.insert(var_name.clone());
                    // `const` unless a later `while` loop reassigns this variable.
                    let keyword = if reassigned.contains(&var_name) { "let" } else { "const" };
                    if self.typed {
                        let ty = if is_str_literal { "string" } else { "Quantity" };
                        main_stmts.push(format!("{} {}: {} = {};", keyword, var_name, ty, val));
                    } else {
                        main_stmts.push(format!("{} {} = {};", keyword, var_name, val));
                    }
                    main_stmts.push(format!("console.log(`{}: ${{{}}}`);", node.name, var_name));
                }
                Statement::Expr(expr) => {
                    if let Some((kind, a, b)) = super::as_assert_call(expr) {
                        let a_code = self.generate_expr(a)?;
                        let b_code = self.generate_expr(b)?;
                        let method = if kind == "assert" { "physAssert" } else { "physExactAssert" };
                        main_stmts.push(format!("{}.{}({});", a_code, method, b_code));
                    } else {
                        let val = self.generate_expr(expr)?;
                        main_stmts.push(format!("console.log({});", val));
                    }
                }
                Statement::While { .. } => {
                    main_stmts.push(self.generate_statement(stmt, &mut main_declared_vars)?);
                }
                _ => {}
            }
        }

        for func in functions {
            out.push_str(&func);
            out.push('\n');
        }

        for stmt in main_stmts {
            out.push_str(&stmt);
            out.push('\n');
        }

        Ok(out)
    }
}

impl JsTranspiler {
    fn generate_function_def_stmt(&self, f: &FunctionDefNode) -> Result<String, CodegenError> {
        let mut out = String::new();
        let params: Vec<String> = f
            .params
            .iter()
            .map(|p| {
                if self.typed {
                    format!("{}: Quantity", snake_to_camel(p))
                } else {
                    snake_to_camel(p)
                }
            })
            .collect();
        let ret_ty = if self.typed { ": Quantity" } else { "" };
        out.push_str(&format!("function {}({}){} {{\n", snake_to_camel(&f.name), params.join(", "), ret_ty));

        let mut declared_vars: HashSet<String> = f.params.iter().map(|p| snake_to_camel(p)).collect();
        let last_idx = f.body_stmts.len().saturating_sub(1);
        for (i, stmt) in f.body_stmts.iter().enumerate() {
            if i == last_idx {
                if let Statement::Expr(ref e) = stmt {
                    out.push_str(&format!("    return {};\n", self.generate_expr(e)?));
                } else {
                    out.push_str(&format!("    {};\n", self.generate_statement(stmt, &mut declared_vars)?));
                }
            } else {
                out.push_str(&format!("    {};\n", self.generate_statement(stmt, &mut declared_vars)?));
            }
        }
        out.push_str("}\n");
        Ok(out)
    }

    fn generate_statement(&self, stmt: &Statement, declared_vars: &mut HashSet<String>) -> Result<String, CodegenError> {
        match stmt {
            Statement::FunctionDef(f) => self.generate_function_def_stmt(f),
            Statement::Assignment(node) => {
                let val = self.generate_expr(&node.value)?;
                let var_name = snake_to_camel(&node.name);
                if declared_vars.contains(&var_name) {
                    Ok(format!("{} = {}", var_name, val))
                } else {
                    declared_vars.insert(var_name.clone());
                    Ok(format!("let {} = {}", var_name, val))
                }
            }
            Statement::Expr(expr) => self.generate_expr(expr),
            Statement::Return(expr) => Ok(format!("return {}", self.generate_expr(expr)?)),
            Statement::GuardReturn { cond, value } => {
                Ok(format!("if ({}) {{ return {}; }}", self.generate_expr(cond)?, self.generate_expr(value)?))
            }
            Statement::While { cond, body, .. } => {
                let cond_str = self.generate_expr(cond)?;
                let mut lines = Vec::new();
                for s in body {
                    let stmt_code = self.generate_statement(s, declared_vars)?;
                    if !stmt_code.is_empty() {
                        let stmt_with_semi = if stmt_code.ends_with(';') || stmt_code.ends_with('}') {
                            stmt_code
                        } else {
                            format!("{};", stmt_code)
                        };
                        for line in stmt_with_semi.lines() {
                            lines.push(format!("  {}", line));
                        }
                    }
                }
                Ok(format!("while ({}) {{\n{}\n}}", cond_str, lines.join("\n")))
            }
            _ => Ok(String::new()),
        }
    }

    fn generate_expr(&self, expr: &Expr) -> Result<String, CodegenError> {
        match expr {
            Expr::Str(text) => {
                let parts = super::split_interpolated(text);
                let mut out = String::from("`");
                for part in &parts {
                    match part {
                        super::StrPart::Text(t) => out.push_str(&escape_template_text(t)),
                        super::StrPart::Expr(e) => {
                            out.push_str("${");
                            out.push_str(&self.generate_expr(e)?);
                            out.push('}');
                        }
                    }
                }
                out.push('`');
                Ok(out)
            }
            Expr::Bool(b) => Ok(if *b { "true" } else { "false" }.to_string()),
            Expr::Identifier(id) => Ok(snake_to_camel(id)),
            Expr::Quantity(q) => {
                if let Some(reason) = q.asymmetric_refusal() {
                    return Err(CodegenError::Generic(reason));
                }
                let mut args = vec![format!("{}", q.magnitude)];

                let is_with_unc = q.uncertainty.is_some();
                if let Some(unc) = q.uncertainty {
                    args.push(format!("{}", unc));
                }
                if let Some(ref unit) = q.unit {
                    args.push(format!("\"{}\"", unit));
                }

                if is_with_unc {
                    Ok(format!("Quantity.withUncertainty({})", args.join(", ")))
                } else {
                    Ok(format!("Quantity.of({})", args.join(", ")))
                }
            }
            Expr::BinaryOp { op, left, right } => {
                let l = self.generate_expr(left)?;
                if *op == BinaryOp::Convert {
                    let unit_str = super::expr_to_unit_string(right);
                    Ok(format!("{}.convertTo(\"{}\")", l, unit_str))
                } else if *op == BinaryOp::Pow {
                    if let Expr::Quantity(q) = &**right {
                        return Ok(format!("{}.pow({})", l, q.magnitude));
                    }
                    let r = self.generate_expr(right)?;
                    Ok(format!("{}.pow({}.getValue())", l, r))
                } else {
                    let r = self.generate_expr(right)?;
                    let method = match op {
                        BinaryOp::Add => "add",
                        BinaryOp::Sub => "subtract",
                        BinaryOp::Mul => "multiply",
                        BinaryOp::Div => "divide",
                        BinaryOp::Pow => unreachable!(),
                        BinaryOp::Convert => unreachable!(),
                        BinaryOp::Range => return Err(super::range_is_not_transpilable()),
                    };
                    Ok(format!("{}.{}({})", l, method, r))
                }
            }
            Expr::FunctionCall { name, args, kwargs } => {
                if let Some((op_sym, l, r)) = super::as_comparison_op(expr) {
                    let l_str = self.generate_expr(l)?;
                    let r_str = self.generate_expr(r)?;
                    return Ok(format!("({}.getValue() {} {}.getValue())", l_str, op_sym, r_str));
                }
                if !kwargs.is_empty() {
                    return Err(CodegenError::Generic(format!(
                        "Named arguments are not supported in JS/TS codegen (call to '{}')",
                        name
                    )));
                }
                if (name == "assert" || name == "exact_assert") && args.len() == 2 {
                    return Err(CodegenError::Generic(format!(
                        "'{}' can only be used as a standalone statement, not nested inside an expression",
                        name
                    )));
                }
                let mut arg_strs = Vec::new();
                for a in args {
                    arg_strs.push(self.generate_expr(a)?);
                }
                Ok(format!("{}({})", snake_to_camel(name), arg_strs.join(", ")))
            }
            Expr::ForExpr { var, iterable, body } => {
                let it_str = self.generate_expr(iterable)?;
                let var_str = snake_to_camel(var);
                let body_str = self.generate_expr(body)?;
                Ok(format!("({}).map(({}) => {})", it_str, var_str, body_str))
            }
        }
    }
}

/// Escapes the characters that would otherwise break out of a template literal:
/// backslash, backtick, and a literal `${` (which would open an interpolation).
fn escape_template_text(s: &str) -> String {
    s.replace('\\', "\\\\").replace('`', "\\`").replace("${", "\\${")
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ast::QuantityNode;

    #[test]
    fn test_transpile_function_def_js() {
        let transpiler = JsTranspiler::default();
        let func = Statement::FunctionDef(FunctionDefNode {
            name: "kinetic_energy".to_string(),
            params: vec!["m".to_string(), "v".to_string()],
            param_units: vec![None, None],
            body_stmts: vec![Statement::Expr(Expr::BinaryOp {
                op: BinaryOp::Mul,
                left: Box::new(Expr::Identifier("m".to_string())),
                right: Box::new(Expr::Identifier("v".to_string())),
            })],
            body_lines: vec![],
            decorators: Vec::new(),
            doc: None,
        });

        let result = transpiler.generate_statement(&func, &mut HashSet::new()).unwrap();
        assert!(result.contains("function kineticEnergy(m, v)"));
        assert!(result.contains("return m.multiply(v);"));
    }

    #[test]
    fn test_transpile_function_def_ts() {
        let transpiler = JsTranspiler { typed: true };
        let func = Statement::FunctionDef(FunctionDefNode {
            name: "kinetic_energy".to_string(),
            params: vec!["m".to_string(), "v".to_string()],
            param_units: vec![None, None],
            body_stmts: vec![Statement::Expr(Expr::BinaryOp {
                op: BinaryOp::Mul,
                left: Box::new(Expr::Identifier("m".to_string())),
                right: Box::new(Expr::Identifier("v".to_string())),
            })],
            body_lines: vec![],
            decorators: Vec::new(),
            doc: None,
        });

        let result = transpiler.generate_statement(&func, &mut HashSet::new()).unwrap();
        assert!(result.contains("function kineticEnergy(m: Quantity, v: Quantity): Quantity"));
        assert!(result.contains("return m.multiply(v);"));
    }

    #[test]
    fn test_transpile_quantity_with_uncertainty_js() {
        let transpiler = JsTranspiler::default();
        let q = Expr::Quantity(QuantityNode {
            magnitude: 75.0,
            uncertainty: Some(0.5),
            uncertainty_lower: None,
            is_sigma: false,
            unit: Some("kg".to_string()),
        });
        let result = transpiler.generate_expr(&q).unwrap();
        assert_eq!(result, "Quantity.withUncertainty(75, 0.5, \"kg\")");
    }

    #[test]
    fn test_transpile_quantity_with_uncertainty_ts() {
        let transpiler = JsTranspiler { typed: true };
        let q = Expr::Quantity(QuantityNode {
            magnitude: 75.0,
            uncertainty: Some(0.5),
            uncertainty_lower: None,
            is_sigma: false,
            unit: Some("kg".to_string()),
        });
        let result = transpiler.generate_expr(&q).unwrap();
        assert_eq!(result, "Quantity.withUncertainty(75, 0.5, \"kg\")");
    }

    #[test]
    fn transpiles_bool_literals_js() {
        let tp = JsTranspiler::default();
        assert_eq!(tp.generate_expr(&Expr::Bool(true)).unwrap(), "true");
        assert_eq!(tp.generate_expr(&Expr::Bool(false)).unwrap(), "false");
    }

    #[test]
    fn transpiles_assert_call_to_phys_assert_call_js() {
        let transpiler = JsTranspiler::default();
        let program = crate::parser::parse_phs("assert(1.0 km, 1000.0 m)").unwrap();
        let code = transpiler.generate_program(&program).unwrap();
        assert!(code.contains(".physAssert("), "expected physAssert call:\n{code}");
    }

    #[test]
    fn transpiles_exact_assert_call_to_phys_exact_assert_call_ts() {
        let transpiler = JsTranspiler { typed: true };
        let program = crate::parser::parse_phs("exact_assert(5.0 m, 5.0 m)").unwrap();
        let code = transpiler.generate_program(&program).unwrap();
        assert!(code.contains(".physExactAssert("), "expected physExactAssert call:\n{code}");
    }

    #[test]
    fn rejects_assert_used_as_a_nested_expression_js() {
        let transpiler = JsTranspiler::default();
        let program = crate::parser::parse_phs("x = assert(1.0 m, 1.0 m)").unwrap();
        assert!(transpiler.generate_program(&program).is_err());
    }

    #[test]
    fn test_transpile_for_expr_and_while_stmt_js() {
        let tp = JsTranspiler::default();
        let for_expr = Expr::ForExpr {
            var: "x".to_string(),
            iterable: Box::new(Expr::Identifier("items".to_string())),
            body: Box::new(Expr::Identifier("x".to_string())),
        };
        let code_for = tp.generate_expr(&for_expr).unwrap();
        assert_eq!(code_for, "(items).map((x) => x)");

        let while_stmt = Statement::While {
            cond: Expr::Identifier("flag".to_string()),
            body: vec![Statement::Return(Expr::Identifier("x".to_string()))],
            body_lines: vec![],
        };
        let code_while = tp.generate_statement(&while_stmt, &mut HashSet::new()).unwrap();
        assert_eq!(code_while, "while (flag) {\n  return x;\n}");
    }

    #[test]
    fn test_js_reassignment_in_while_loop() {
        let tp = JsTranspiler::default();
        let program = crate::parser::parse_phs("i = 0\nwhile i < 5 {\n  i = i + 1\n}").unwrap();
        let code = tp.generate_program(&program).unwrap();
        assert!(code.contains("let i = "), "expected mutable declaration:\n{code}");
        assert!(code.contains("i = i.add("), "expected reassignment without redeclaration:\n{code}");
        assert!(!code.contains("let i = i.add("), "reassignment should not redeclare inside the loop:\n{code}");
    }
}
