use crate::ast::{BinaryOp, Expr, FunctionDefNode, Program, Statement};
use crate::codegen::{CodeGenerator, CodegenError};

#[derive(Debug, Clone, Default)]
pub struct JsTranspiler {
    /// false = plain JavaScript, true = TypeScript (adds type annotations).
    pub typed: bool,
}

impl CodeGenerator for JsTranspiler {
    fn generate_program(&self, program: &Program) -> Result<String, CodegenError> {
        let mut out = String::new();
        out.push_str(concat!("// Generated by PhysureScript (PHS) Compiler v", env!("CARGO_PKG_VERSION"), "\n"));
        out.push_str("import { Quantity } from \"physure\";\n\n");

        let mut functions = Vec::new();
        let mut main_stmts = Vec::new();

        for stmt in &program.statements {
            match stmt {
                Statement::FunctionDef(f) => {
                    functions.push(self.generate_function_def_stmt(f)?);
                }
                Statement::Assignment(node) => {
                    let val = self.generate_expr(&node.value)?;
                    let var_name = snake_to_camel(&node.name);
                    let is_str_literal = matches!(&node.value, Expr::Str(_));
                    if self.typed {
                        let ty = if is_str_literal { "string" } else { "Quantity" };
                        main_stmts.push(format!("const {}: {} = {};", var_name, ty, val));
                    } else {
                        main_stmts.push(format!("const {} = {};", var_name, val));
                    }
                    main_stmts.push(format!("console.log(`{}: ${{{}}}`);", node.name, var_name));
                }
                Statement::Expr(expr) => {
                    let val = self.generate_expr(expr)?;
                    main_stmts.push(format!("console.log({});", val));
                }
                _ => {}
            }
        }

        for func in functions {
            out.push_str(&func);
            out.push('\n');
        }

        for stmt in main_stmts {
            out.push_str(&stmt);
            out.push('\n');
        }

        Ok(out)
    }
}

impl JsTranspiler {
    fn generate_function_def_stmt(&self, f: &FunctionDefNode) -> Result<String, CodegenError> {
        let mut out = String::new();
        let params: Vec<String> = f
            .params
            .iter()
            .map(|p| {
                if self.typed {
                    format!("{}: Quantity", snake_to_camel(p))
                } else {
                    snake_to_camel(p)
                }
            })
            .collect();
        let ret_ty = if self.typed { ": Quantity" } else { "" };
        out.push_str(&format!("function {}({}){} {{\n", snake_to_camel(&f.name), params.join(", "), ret_ty));

        let last_idx = f.body_stmts.len().saturating_sub(1);
        for (i, stmt) in f.body_stmts.iter().enumerate() {
            if i == last_idx {
                if let Statement::Expr(ref e) = stmt {
                    out.push_str(&format!("    return {};\n", self.generate_expr(e)?));
                } else {
                    out.push_str(&format!("    {};\n", self.generate_statement(stmt)?));
                }
            } else {
                out.push_str(&format!("    {};\n", self.generate_statement(stmt)?));
            }
        }
        out.push_str("}\n");
        Ok(out)
    }

    fn generate_statement(&self, stmt: &Statement) -> Result<String, CodegenError> {
        match stmt {
            Statement::FunctionDef(f) => self.generate_function_def_stmt(f),
            Statement::Return(expr) => Ok(format!("return {}", self.generate_expr(expr)?)),
            Statement::GuardReturn { cond, value } => {
                Ok(format!("if ({}) {{ return {}; }}", self.generate_expr(cond)?, self.generate_expr(value)?))
            }
            _ => Ok(String::new()),
        }
    }

    fn generate_expr(&self, expr: &Expr) -> Result<String, CodegenError> {
        match expr {
            Expr::Str(text) => {
                let parts = super::split_interpolated(text);
                let mut out = String::from("`");
                for part in &parts {
                    match part {
                        super::StrPart::Text(t) => out.push_str(&escape_template_text(t)),
                        super::StrPart::Expr(e) => {
                            out.push_str("${");
                            out.push_str(&self.generate_expr(e)?);
                            out.push('}');
                        }
                    }
                }
                out.push('`');
                Ok(out)
            }
            Expr::Identifier(id) => Ok(snake_to_camel(id)),
            Expr::Quantity(q) => {
                if let Some(reason) = q.asymmetric_refusal() {
                    return Err(CodegenError::Generic(reason));
                }
                let mut args = vec![format!("{}", q.magnitude)];

                let is_with_unc = q.uncertainty.is_some();
                if let Some(unc) = q.uncertainty {
                    args.push(format!("{}", unc));
                }
                if let Some(ref unit) = q.unit {
                    args.push(format!("\"{}\"", unit));
                }

                if is_with_unc {
                    Ok(format!("Quantity.withUncertainty({})", args.join(", ")))
                } else {
                    Ok(format!("Quantity.of({})", args.join(", ")))
                }
            }
            Expr::BinaryOp { op, left, right } => {
                let l = self.generate_expr(left)?;
                if *op == BinaryOp::Convert {
                    let unit_str = super::expr_to_unit_string(right);
                    Ok(format!("{}.convertTo(\"{}\")", l, unit_str))
                } else if *op == BinaryOp::Pow {
                    if let Expr::Quantity(q) = &**right {
                        return Ok(format!("{}.pow({})", l, q.magnitude));
                    }
                    let r = self.generate_expr(right)?;
                    Ok(format!("{}.pow({}.getValue())", l, r))
                } else {
                    let r = self.generate_expr(right)?;
                    let method = match op {
                        BinaryOp::Add => "add",
                        BinaryOp::Sub => "subtract",
                        BinaryOp::Mul => "multiply",
                        BinaryOp::Div => "divide",
                        BinaryOp::Pow => unreachable!(),
                        BinaryOp::Convert => unreachable!(),
                        BinaryOp::Range => return Err(super::range_is_not_transpilable()),
                    };
                    Ok(format!("{}.{}({})", l, method, r))
                }
            }
            Expr::FunctionCall { name, args, kwargs } => {
                if !kwargs.is_empty() {
                    return Err(CodegenError::Generic(format!(
                        "Named arguments are not supported in JS/TS codegen (call to '{}')",
                        name
                    )));
                }
                let mut arg_strs = Vec::new();
                for a in args {
                    arg_strs.push(self.generate_expr(a)?);
                }
                Ok(format!("{}({})", snake_to_camel(name), arg_strs.join(", ")))
            }
        }
    }
}

fn snake_to_camel(s: &str) -> String {
    let mut result = String::new();
    let mut capitalize_next = false;
    for (i, c) in s.chars().enumerate() {
        if c == '_' {
            capitalize_next = true;
        } else {
            if capitalize_next && i > 0 {
                result.push(c.to_ascii_uppercase());
            } else {
                result.push(c);
            }
            capitalize_next = false;
        }
    }
    result
}

/// Escapes the characters that would otherwise break out of a template literal:
/// backslash, backtick, and a literal `${` (which would open an interpolation).
fn escape_template_text(s: &str) -> String {
    s.replace('\\', "\\\\").replace('`', "\\`").replace("${", "\\${")
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ast::QuantityNode;

    #[test]
    fn test_transpile_function_def_js() {
        let transpiler = JsTranspiler::default();
        let func = Statement::FunctionDef(FunctionDefNode {
            name: "kinetic_energy".to_string(),
            params: vec!["m".to_string(), "v".to_string()],
            param_units: vec![None, None],
            body_stmts: vec![Statement::Expr(Expr::BinaryOp {
                op: BinaryOp::Mul,
                left: Box::new(Expr::Identifier("m".to_string())),
                right: Box::new(Expr::Identifier("v".to_string())),
            })],
            decorators: Vec::new(),
        });

        let result = transpiler.generate_statement(&func).unwrap();
        assert!(result.contains("function kineticEnergy(m, v)"));
        assert!(result.contains("return m.multiply(v);"));
    }

    #[test]
    fn test_transpile_function_def_ts() {
        let transpiler = JsTranspiler { typed: true };
        let func = Statement::FunctionDef(FunctionDefNode {
            name: "kinetic_energy".to_string(),
            params: vec!["m".to_string(), "v".to_string()],
            param_units: vec![None, None],
            body_stmts: vec![Statement::Expr(Expr::BinaryOp {
                op: BinaryOp::Mul,
                left: Box::new(Expr::Identifier("m".to_string())),
                right: Box::new(Expr::Identifier("v".to_string())),
            })],
            decorators: Vec::new(),
        });

        let result = transpiler.generate_statement(&func).unwrap();
        assert!(result.contains("function kineticEnergy(m: Quantity, v: Quantity): Quantity"));
        assert!(result.contains("return m.multiply(v);"));
    }

    #[test]
    fn test_transpile_quantity_with_uncertainty_js() {
        let transpiler = JsTranspiler::default();
        let q = Expr::Quantity(QuantityNode {
            magnitude: 75.0,
            uncertainty: Some(0.5),
            uncertainty_lower: None,
            is_sigma: false,
            unit: Some("kg".to_string()),
        });
        let result = transpiler.generate_expr(&q).unwrap();
        assert_eq!(result, "Quantity.withUncertainty(75, 0.5, \"kg\")");
    }

    #[test]
    fn test_transpile_quantity_with_uncertainty_ts() {
        let transpiler = JsTranspiler { typed: true };
        let q = Expr::Quantity(QuantityNode {
            magnitude: 75.0,
            uncertainty: Some(0.5),
            uncertainty_lower: None,
            is_sigma: false,
            unit: Some("kg".to_string()),
        });
        let result = transpiler.generate_expr(&q).unwrap();
        assert_eq!(result, "Quantity.withUncertainty(75, 0.5, \"kg\")");
    }
}
