use crate::ast::{
    Program, Statement, ImportNode, ImportSpecifier, ExportNode,
    FunctionDefNode, AssignmentNode, Expr, BinaryOp, QuantityNode
};
use super::{CodeGenerator, CodegenError};

pub struct PythonTranspiler;

impl CodeGenerator for PythonTranspiler {
    fn generate_program(&self, program: &Program) -> Result<String, CodegenError> {
        let mut out = String::from(concat!(
            "# Generated by PhysureScript (PHS) Compiler v0.2.4\n",
            "import math\n",
            "from physure import Q_, Quantity\n\n",
            "try:\n",
            "    from physure.builtins import vector, gradient, trapz, solve, deriv, integral\n",
            "except ImportError:\n",
            "    def vector(*args): return list(args)\n\n"
        ));
        
        for stmt in &program.statements {
            let stmt_str = self.generate_statement(stmt)?;
            if !stmt_str.is_empty() {
                out.push_str(&stmt_str);
                out.push('\n');
            }
        }
        
        Ok(out)
    }
}

fn sanitize_identifier(name: &str) -> String {
    name.replace('≈', "_approx")
        .replace('±', "_pm")
        .replace('σ', "_sigma")
        .replace('π', "pi")
        .replace('Δ', "delta")
        .replace('μ', "micro")
        .replace('λ', "lambda")
        .replace('θ', "theta")
        .replace('Ω', "omega")
}

impl PythonTranspiler {
    fn generate_statement(&self, stmt: &Statement) -> Result<String, CodegenError> {
        match stmt {
            Statement::Import(node) => self.generate_import(node),
            Statement::Export(node) => self.generate_export(node),
            Statement::FunctionDef(node) => self.generate_function_def(node),
            Statement::Assignment(node) => self.generate_assignment(node),
            Statement::Expr(expr) => self.generate_expr(expr),
        }
    }
    
    fn generate_import(&self, node: &ImportNode) -> Result<String, CodegenError> {
        let py_path = node.path.replace("/", ".");
        let module = format!("physure.{}", py_path);
        
        match &node.specifier {
            ImportSpecifier::Wildcard => Ok(format!("from {} import *", module)),
            ImportSpecifier::Symbols(syms) => {
                let mut sym_strs = Vec::new();
                for sym in syms {
                    if let Some(alias) = &sym.alias {
                        sym_strs.push(format!("{} as {}", sym.name, alias));
                    } else {
                        sym_strs.push(sym.name.clone());
                    }
                }
                Ok(format!("from {} import {}", module, sym_strs.join(", ")))
            }
            ImportSpecifier::ModuleAlias(alias) => {
                Ok(format!("import {} as {}", module, alias))
            }
        }
    }
    
    fn generate_export(&self, node: &ExportNode) -> Result<String, CodegenError> {
        Ok(format!("__all_exports__[\"{}\"] = {}", node.export_name, node.symbol))
    }
    
    fn generate_function_def(&self, node: &FunctionDefNode) -> Result<String, CodegenError> {
        let params = node.params.join(", ");
        let last_idx = node.body_stmts.len().saturating_sub(1);
        let mut lines = Vec::new();
        for (i, stmt) in node.body_stmts.iter().enumerate() {
            let stmt_code = self.generate_statement(stmt)?;
            if i == last_idx {
                if let Statement::Expr(ref e) = stmt {
                    lines.push(format!("    return {}", self.generate_expr(e)?));
                } else {
                    lines.push(format!("    {}", stmt_code));
                }
            } else {
                lines.push(format!("    {}", stmt_code));
            }
        }
        Ok(format!("def {}({}):\n{}", node.name, params, lines.join("\n")))
    }
    
    fn generate_assignment(&self, node: &AssignmentNode) -> Result<String, CodegenError> {
        let val_str = self.generate_expr(&node.value)?;
        Ok(format!("{} = {}", sanitize_identifier(&node.name), val_str))
    }
    
    fn generate_expr(&self, expr: &Expr) -> Result<String, CodegenError> {
        match expr {
            Expr::Quantity(node) => self.generate_quantity(node),
            Expr::Identifier(name) => {
                if name.starts_with('`') || name.contains('\n') {
                    let clean = name.trim_matches('`').trim();
                    Ok(format!("\"\"\"{}\"\"\"", clean))
                } else {
                    Ok(sanitize_identifier(name))
                }
            }
            Expr::BinaryOp { op, left, right } => {
                let l_str = self.generate_expr(left)?;
                let r_str = self.generate_expr(right)?;
                if *op == BinaryOp::Convert {
                    let clean_unit = r_str.trim_matches('(').trim_matches(')').trim_matches('"');
                    Ok(format!("{}.to(\"{}\")", l_str, clean_unit))
                } else if *op == BinaryOp::Pow {
                    if let Expr::Quantity(q) = &**right {
                        if q.unit.is_none() || q.unit.as_deref() == Some("") {
                            return Ok(format!("({} ** {:?})", l_str, q.magnitude));
                        }
                    }
                    Ok(format!("({} ** {})", l_str, r_str))
                } else {
                    let op_str = match op {
                        BinaryOp::Add => "+",
                        BinaryOp::Sub => "-",
                        BinaryOp::Mul => "*",
                        BinaryOp::Div => "/",
                        BinaryOp::Pow => unreachable!(),
                        BinaryOp::Convert => unreachable!(),
                    };
                    Ok(format!("({} {} {})", l_str, op_str, r_str))
                }
            }
            Expr::FunctionCall { name, args } => {
                let mut arg_strs = Vec::new();
                for (i, arg) in args.iter().enumerate() {
                    let arg_s = self.generate_expr(arg)?;
                    if name == "format" && i == 1 && !arg_s.starts_with('"') {
                        arg_strs.push(format!("\"{}\"", arg_s));
                    } else {
                        arg_strs.push(arg_s);
                    }
                }
                Ok(format!("{}({})", sanitize_identifier(name), arg_strs.join(", ")))
            }
        }
    }
    
    fn generate_quantity(&self, node: &QuantityNode) -> Result<String, CodegenError> {
        let unit_str = node.unit.as_deref().unwrap_or("");
        let unc_str = if let Some(unc) = node.uncertainty {
            format!(", uncertainty={:?}", unc)
        } else {
            String::new()
        };
        Ok(format!("Q_({:?}, \"{}\"{})", node.magnitude, unit_str, unc_str))
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ast::{ImportSymbol, Program, Statement, FunctionDefNode, Expr, QuantityNode, BinaryOp, ImportNode, ImportSpecifier};

    #[test]
    fn test_transpile_quantity_with_uncertainty() {
        let tp = PythonTranspiler;
        let q = QuantityNode {
            magnitude: 5.0,
            uncertainty: Some(0.1),
            is_sigma: false,
            unit: Some("m".to_string()),
        };
        let res = tp.generate_quantity(&q).unwrap();
        assert_eq!(res, "Q_(5.0, \"m\", uncertainty=0.1)");
    }

    #[test]
    fn test_transpile_function_def_and_import() {
        let tp = PythonTranspiler;
        
        let import_node = ImportNode {
            path: "physics/constants".to_string(),
            specifier: ImportSpecifier::Symbols(vec![
                ImportSymbol { name: "g".to_string(), alias: None }
            ]),
        };
        
        let fn_node = FunctionDefNode {
            name: "foo".to_string(),
            params: vec!["a".to_string(), "b".to_string()],
            body_stmts: vec![Statement::Expr(Expr::BinaryOp {
                op: BinaryOp::Mul,
                left: Box::new(Expr::Identifier("a".to_string())),
                right: Box::new(Expr::Identifier("b".to_string())),
            })],
        };

        let prog = Program {
            statements: vec![
                Statement::Import(import_node),
                Statement::FunctionDef(fn_node),
            ],
        };

        let res = tp.generate_program(&prog).unwrap();
        assert!(res.contains("from physure.physics.constants import g"));
        assert!(res.contains("def foo(a, b):\n    return (a * b)"));
    }
}
