use physure_core::error::PhysureResult;
use crate::ast::{BinaryOp, Expr, Statement, UnaryOp};
use super::CodeGenerator;
use std::collections::HashSet;

pub struct PythonCodeGenerator {
    known_vars: HashSet<String>,
}

impl PythonCodeGenerator {
    pub fn new() -> Self {
        Self {
            known_vars: HashSet::new(),
        }
    }
}

impl CodeGenerator for PythonCodeGenerator {
    fn generate_program(&mut self, statements: &[Statement]) -> PhysureResult<String> {
        let mut out = String::new();
        out.push_str("# Generated by Physure Native AST Codegen\n");
        out.push_str("from physure import Q_, Quantity\n\n");

        for stmt in statements {
            let stmt_code = self.generate_statement(stmt)?;
            if !stmt_code.is_empty() {
                out.push_str(&format!("{}\n", stmt_code));
            }
        }

        Ok(out)
    }

    fn generate_statement(&mut self, stmt: &Statement) -> PhysureResult<String> {
        match stmt {
            Statement::Assign { name, expr } => {
                let expr_str = self.generate_expr(expr)?;
                self.known_vars.insert(name.clone());
                Ok(format!("{} = {}", name, expr_str))
            }
            Statement::Query { expr } => {
                let expr_str = self.generate_expr(expr)?;
                Ok(format!("print({})", expr_str))
            }
            Statement::AssignAndQuery { name, expr } => {
                let expr_str = self.generate_expr(expr)?;
                self.known_vars.insert(name.clone());
                Ok(format!("{} = {}\nprint({})", name, expr_str, name))
            }
            Statement::Assert { left, right, op: _ } => {
                let l_str = self.generate_expr(left)?;
                let r_str = self.generate_expr(right)?;
                Ok(format!("print(abs({}.magnitude - {}.magnitude) <= 0.5)", l_str, r_str))
            }
            Statement::FnDef { name, params, body } => {
                let params_str = params.iter().map(|p| p.name.as_str()).collect::<Vec<_>>().join(", ");
                let mut body_str = String::new();
                for b_stmt in body {
                    body_str.push_str(&format!("    {}\n", self.generate_statement(b_stmt)?));
                }
                Ok(format!("def {}({}):\n{}    return Q_(0.0, '')", name, params_str, body_str))
            }
            Statement::DisplayText(text) => {
                let escaped = text.replace('\\', "\\\\").replace('"', "\\\"").replace('\n', "\\n");
                Ok(format!("print(f\"{}\")", escaped))
            }
            Statement::ExprStmt(expr) => {
                let expr_str = self.generate_expr(expr)?;
                Ok(format!("print({})", expr_str))
            }
        }
    }

    fn generate_expr(&mut self, expr: &Expr) -> PhysureResult<String> {
        match expr {
            Expr::Number(n) => Ok(format!("Q_({:?}, '')", n)),
            Expr::Ident(name) => Ok(name.clone()),
            Expr::StringLiteral(s) => Ok(format!("\"{}\"", s)),
            Expr::Unary { op, expr } => {
                let inner = self.generate_expr(expr)?;
                match op {
                    UnaryOp::Neg => Ok(format!("(-{})", inner)),
                    UnaryOp::Sqrt => Ok(format!("({} ** 0.5)", inner)),
                }
            }
            Expr::Binary { op, left, right } => {
                let l_str = self.generate_expr(left)?;
                let r_str = self.generate_expr(right)?;
                match op {
                    BinaryOp::Add => Ok(format!("({} + {})", l_str, r_str)),
                    BinaryOp::Sub => Ok(format!("({} - {})", l_str, r_str)),
                    BinaryOp::Mul => Ok(format!("({} * {})", l_str, r_str)),
                    BinaryOp::Div => Ok(format!("({} / {})", l_str, r_str)),
                    BinaryOp::Pow => Ok(format!("({} ** {})", l_str, r_str)),
                    _ => Ok(format!("({} + {})", l_str, r_str)),
                }
            }
            Expr::ImplicitMul { left, right } => {
                if let Expr::Number(n) = **left {
                    if let Expr::Ident(ref u) = **right {
                        return Ok(format!("Q_({:?}, '{}')", n, u));
                    }
                }
                let l_str = self.generate_expr(left)?;
                let r_str = self.generate_expr(right)?;
                Ok(format!("({} * {})", l_str, r_str))
            }
            Expr::Call { name, args } => {
                let formatted_args = args.iter().map(|a| self.generate_expr(a)).collect::<PhysureResult<Vec<_>>>()?.join(", ");
                Ok(format!("{}({})", name, formatted_args))
            }
            Expr::Convert { expr, target_unit } => {
                let inner = self.generate_expr(expr)?;
                Ok(format!("{}.to('{}')", inner, target_unit))
            }
            Expr::FormatSig { expr, spec: _ } => self.generate_expr(expr),
            Expr::Vector(elems) => {
                let q_elems = elems.iter().map(|e| self.generate_expr(e)).collect::<PhysureResult<Vec<_>>>()?.join(", ");
                Ok(format!("[{}]", q_elems))
            }
            _ => Ok(format!("Q_(0.0, '')")),
        }
    }
}
