use crate::ast::{
    Program, Statement, ImportNode, ImportSpecifier, ExportNode,
    FunctionDefNode, AssignmentNode, Expr, BinaryOp, QuantityNode
};
use super::{CodeGenerator, CodegenError};

pub struct PythonTranspiler;

impl CodeGenerator for PythonTranspiler {
    fn generate_program(&self, program: &Program) -> Result<String, CodegenError> {
        let mut out = String::from(concat!(
            "# Generated by PhysureScript (PHS) Compiler v", env!("CARGO_PKG_VERSION"), "\n",
            "import math\n",
            "from physure import Q_, Quantity, PhyEquation, PhyFunction, phy_function\n\n",
            "try:\n",
            "    from physure.builtins import vector, gradient, trapz, solve, deriv, integral\n",
            "except ImportError:\n",
            "    def vector(*args): return list(args)\n\n"
        ));
        
        for stmt in &program.statements {
            match stmt {
                Statement::Assignment(node) => {
                    let stmt_str = self.generate_assignment(node)?;
                    out.push_str(&stmt_str);
                    out.push('\n');
                    out.push_str(&format!("print(f\"{}: {{{}}}\")\n", node.name, sanitize_identifier(&node.name)));
                }
                Statement::Expr(expr) => {
                    if let Some((kind, a, b)) = super::as_assert_call(expr) {
                        let a_code = self.generate_expr(a)?;
                        let b_code = self.generate_expr(b)?;
                        let line = if kind == "assert" {
                            format!(
                                "assert ({a}).approx_eq({b}, 1e-9, 1e-12), f\"assert failed: {{{a}}} != {{{b}}}\"",
                                a = a_code, b = b_code
                            )
                        } else {
                            format!(
                                "assert ({a}).exact_eq({b}), f\"exact_assert failed: {{{a}}} != {{{b}}}\"",
                                a = a_code, b = b_code
                            )
                        };
                        out.push_str(&line);
                        out.push('\n');
                    } else {
                        let expr_str = self.generate_expr(expr)?;
                        out.push_str(&format!("print({})\n", expr_str));
                    }
                }
                _ => {
                    let stmt_str = self.generate_statement(stmt)?;
                    if !stmt_str.is_empty() {
                        out.push_str(&stmt_str);
                        out.push('\n');
                    }
                }
            }
        }
        
        Ok(out)
    }
}

fn sanitize_identifier(name: &str) -> String {
    name.replace('≈', "_approx")
        .replace('±', "_pm")
        .replace('σ', "_sigma")
        .replace('π', "pi")
        .replace('Δ', "delta")
        .replace('μ', "micro")
        .replace('λ', "lambda")
        .replace('θ', "theta")
        .replace('Ω', "omega")
}

impl PythonTranspiler {
    fn generate_statement(&self, stmt: &Statement) -> Result<String, CodegenError> {
        match stmt {
            Statement::Import(node) => self.generate_import(node),
            Statement::Export(node) => self.generate_export(node),
            Statement::FunctionDef(node) => self.generate_function_def(node),
            Statement::Assignment(node) => self.generate_assignment(node),
            Statement::Expr(expr) => self.generate_expr(expr),
            Statement::Return(expr) => Ok(format!("return {}", self.generate_expr(expr)?)),
            Statement::GuardReturn { cond, value } => {
                Ok(format!("if {}: return {}", self.generate_expr(cond)?, self.generate_expr(value)?))
            }
        }
    }
    
    fn generate_import(&self, node: &ImportNode) -> Result<String, CodegenError> {
        let py_path = node.path.replace("/", ".");
        if py_path == "calc" || py_path == "builtins" {
            return Ok(format!("# Builtin module '{}' imported", py_path));
        }
        let module = format!("physure.{}", py_path);
        
        match &node.specifier {
            ImportSpecifier::Wildcard => Ok(format!("from {} import *", module)),
            ImportSpecifier::Symbols(syms) => {
                let mut sym_strs = Vec::new();
                for sym in syms {
                    if let Some(alias) = &sym.alias {
                        sym_strs.push(format!("{} as {}", sym.name, alias));
                    } else {
                        sym_strs.push(sym.name.clone());
                    }
                }
                Ok(format!("from {} import {}", module, sym_strs.join(", ")))
            }
            ImportSpecifier::ModuleAlias(alias) => {
                Ok(format!("import {} as {}", module, alias))
            }
        }
    }
    
    fn generate_export(&self, node: &ExportNode) -> Result<String, CodegenError> {
        Ok(format!("__all_exports__[\"{}\"] = {}", node.export_name, node.symbol))
    }
    
    fn generate_function_def(&self, node: &FunctionDefNode) -> Result<String, CodegenError> {
        let params = node.params.join(", ");
        let params_list = format!("{:?}", node.params);
        let last_idx = node.body_stmts.len().saturating_sub(1);
        let mut lines = Vec::new();
        for (i, stmt) in node.body_stmts.iter().enumerate() {
            let stmt_code = self.generate_statement(stmt)?;
            if i == last_idx {
                if let Statement::Expr(ref e) = stmt {
                    lines.push(format!("    return {}", self.generate_expr(e)?));
                } else {
                    lines.push(format!("    {}", stmt_code));
                }
            } else {
                lines.push(format!("    {}", stmt_code));
            }
        }
        Ok(format!("@phy_function(name=\"{}\", params={})\ndef {}({}):\n{}", node.name, params_list, node.name, params, lines.join("\n")))
    }
    
    fn generate_assignment(&self, node: &AssignmentNode) -> Result<String, CodegenError> {
        let val_str = self.generate_expr(&node.value)?;
        if val_str.starts_with('"') && val_str.contains('=') {
            Ok(format!("{} = PhyEquation({})", sanitize_identifier(&node.name), val_str))
        } else {
            Ok(format!("{} = {}", sanitize_identifier(&node.name), val_str))
        }
    }
    
    fn generate_expr(&self, expr: &Expr) -> Result<String, CodegenError> {
        match expr {
            Expr::Quantity(node) => self.generate_quantity(node),
            Expr::Str(text) => {
                // Not an f-string: `{2 m + 3 m}` is PHS, not Python, so each interpolated
                // expression is transpiled on its own and concatenated.
                let parts = super::split_interpolated(text);
                let mut pieces = Vec::new();
                for part in &parts {
                    match part {
                        super::StrPart::Text(t) => pieces.push(format!("{:?}", t)),
                        super::StrPart::Expr(e) => pieces.push(format!("str({})", self.generate_expr(e)?)),
                    }
                }
                Ok(if pieces.len() == 1 { pieces.remove(0) } else { format!("({})", pieces.join(" + ")) })
            }
            Expr::Identifier(name) => {
                if name.starts_with('`') || name.contains('\n') {
                    let clean = name.trim_matches('`').trim();
                    Ok(format!("\"\"\"{}\"\"\"", clean))
                } else {
                    Ok(sanitize_identifier(name))
                }
            }
            Expr::BinaryOp { op, left, right } => {
                let l_str = self.generate_expr(left)?;
                if *op == BinaryOp::Convert {
                    let unit_str = super::expr_to_unit_string(right);
                    Ok(format!("{}.to(\"{}\")", l_str, unit_str))
                } else if *op == BinaryOp::Pow {
                    if let Expr::Quantity(q) = &**right {
                        if q.unit.is_none() || q.unit.as_deref() == Some("") {
                            return Ok(format!("({} ** {:?})", l_str, q.magnitude));
                        }
                    }
                    let r_str = self.generate_expr(right)?;
                    Ok(format!("({} ** {})", l_str, r_str))
                } else {
                    let r_str = self.generate_expr(right)?;
                    let op_str = match op {
                        BinaryOp::Add => "+",
                        BinaryOp::Sub => "-",
                        BinaryOp::Mul => "*",
                        BinaryOp::Div => "/",
                        BinaryOp::Pow => unreachable!(),
                        BinaryOp::Convert => unreachable!(),
                        BinaryOp::Range => return Err(super::range_is_not_transpilable()),
                    };
                    Ok(format!("({} {} {})", l_str, op_str, r_str))
                }
            }
            Expr::FunctionCall { name, args, kwargs } => {
                if (name == "assert" || name == "exact_assert") && kwargs.is_empty() && args.len() == 2 {
                    return Err(CodegenError::Generic(format!(
                        "'{}' can only be used as a standalone statement, not nested inside an expression",
                        name
                    )));
                }
                let mut arg_strs = Vec::new();
                for (i, arg) in args.iter().enumerate() {
                    let arg_s = self.generate_expr(arg)?;
                    if name == "format" && i == 1 && !arg_s.starts_with('"') {
                        arg_strs.push(format!("\"{}\"", arg_s));
                    } else {
                        arg_strs.push(arg_s);
                    }
                }
                for (kwarg_name, kwarg_expr) in kwargs {
                    let kwarg_s = self.generate_expr(kwarg_expr)?;
                    arg_strs.push(format!("{}={}", sanitize_identifier(kwarg_name), kwarg_s));
                }
                Ok(format!("{}({})", sanitize_identifier(name), arg_strs.join(", ")))
            }
        }
    }
    
    fn generate_quantity(&self, node: &QuantityNode) -> Result<String, CodegenError> {
        if let Some(reason) = node.asymmetric_refusal() {
            return Err(CodegenError::Generic(reason));
        }
        let unit_str = node.unit.as_deref().unwrap_or("");
        let unc_str = if let Some(unc) = node.uncertainty {
            format!(", uncertainty={:?}", unc)
        } else {
            String::new()
        };
        Ok(format!("Q_({:?}, \"{}\"{})", node.magnitude, unit_str, unc_str))
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ast::{ImportSymbol, Program, Statement, FunctionDefNode, Expr, QuantityNode, BinaryOp, ImportNode, ImportSpecifier};

    #[test]
    fn test_transpile_quantity_with_uncertainty() {
        let tp = PythonTranspiler;
        let q = QuantityNode {
            magnitude: 5.0,
            uncertainty: Some(0.1),
            uncertainty_lower: None,
            is_sigma: false,
            unit: Some("m".to_string()),
        };
        let res = tp.generate_quantity(&q).unwrap();
        assert_eq!(res, "Q_(5.0, \"m\", uncertainty=0.1)");
    }

    #[test]
    fn test_transpile_function_def_and_import() {
        let tp = PythonTranspiler;
        
        let import_node = ImportNode {
            path: "physics/constants".to_string(),
            specifier: ImportSpecifier::Symbols(vec![
                ImportSymbol { name: "g".to_string(), alias: None }
            ]),
        };
        
        let fn_node = FunctionDefNode {
            name: "foo".to_string(),
            params: vec!["a".to_string(), "b".to_string()],
            param_units: vec![None, None],
            body_stmts: vec![Statement::Expr(Expr::BinaryOp {
                op: BinaryOp::Mul,
                left: Box::new(Expr::Identifier("a".to_string())),
                right: Box::new(Expr::Identifier("b".to_string())),
            })],
            decorators: Vec::new(),
        };

        let prog = Program {
            statements: vec![
                Statement::Import(import_node),
                Statement::FunctionDef(fn_node),
            ],
        };

        let res = tp.generate_program(&prog).unwrap();
        assert!(res.contains("from physure.physics.constants import g"));
        assert!(res.contains("def foo(a, b):\n    return (a * b)"));
    }

    #[test]
    fn transpiles_assert_call_to_a_python_assert_statement() {
        let tp = PythonTranspiler;
        let program = crate::parser::parse_phs("assert(1.0 km, 1000.0 m)").unwrap();
        let code = tp.generate_program(&program).unwrap();
        assert!(code.contains("assert "), "expected a Python assert statement:\n{code}");
        assert!(code.contains(".approx_eq("), "expected approx_eq call:\n{code}");
        assert!(!code.contains("print(assert"), "must not fall through to the generic call path:\n{code}");
    }

    #[test]
    fn transpiles_exact_assert_call_to_equality_assert() {
        let tp = PythonTranspiler;
        let program = crate::parser::parse_phs("exact_assert(5.0 m, 5.0 m)").unwrap();
        let code = tp.generate_program(&program).unwrap();
        assert!(code.contains("assert ") && code.contains(".exact_eq("), "expected an exact_eq assert:\n{code}");
    }

    #[test]
    fn rejects_assert_used_as_a_nested_expression_py() {
        let tp = PythonTranspiler;
        let program = crate::parser::parse_phs("x = assert(1.0 m, 1.0 m)").unwrap();
        assert!(tp.generate_program(&program).is_err());
    }
}
