use crate::ast::*;
use crate::codegen::{CodeGenerator, CodegenError};

pub struct RustTranspiler;

impl CodeGenerator for RustTranspiler {
    fn generate_program(&self, program: &Program) -> Result<String, CodegenError> {
        let mut code = String::from("// Generated by PhysureScript (PHS) Compiler v0.2.4\nuse physure::measurement::Quantity;\n\n");
        let mut top_functions = Vec::new();
        let mut main_statements = Vec::new();

        for stmt in &program.statements {
            match stmt {
                Statement::FunctionDef(node) => {
                    top_functions.push(self.generate_function_def(node)?);
                }
                Statement::Assignment(node) => {
                    main_statements.push(format!("    {}", self.generate_assignment(node)?));
                    main_statements.push(format!("    println!(\"{:?}\", {});", node.name, node.name));
                }
                Statement::Expr(expr) => {
                    let expr_code = self.generate_expr(expr)?;
                    main_statements.push(format!("    println!(\"{:?}\", {});", expr_code, expr_code));
                }
                _ => {}
            }
        }

        for func in top_functions {
            code.push_str(&func);
            code.push_str("\n\n");
        }

        if !main_statements.is_empty() {
            code.push_str("fn main() -> Result<(), Box<dyn std::error::Error>> {\n");
            code.push_str(&main_statements.join("\n"));
            code.push_str("\n    Ok(())\n}\n");
        }

        Ok(code)
    }
}

impl RustTranspiler {
    fn generate_statement(&self, stmt: &Statement) -> Result<String, CodegenError> {
        match stmt {
            Statement::Import(_) => Ok(String::new()),
            Statement::Export(_) => Ok(String::new()),
            Statement::FunctionDef(node) => self.generate_function_def(node),
            Statement::Assignment(node) => self.generate_assignment(node),
            Statement::Expr(expr) => self.generate_expr(expr),
        }
    }

    fn generate_function_def(&self, node: &FunctionDefNode) -> Result<String, CodegenError> {
        let mut params = Vec::new();
        for param in &node.params {
            params.push(format!("{}: Quantity", param));
        }
        let last_idx = node.body_stmts.len().saturating_sub(1);
        let mut body_lines = Vec::new();
        for (i, stmt) in node.body_stmts.iter().enumerate() {
            if i == last_idx {
                if let Statement::Expr(ref e) = stmt {
                    body_lines.push(format!("    {}", self.generate_expr(e)?));
                } else {
                    body_lines.push(format!("    {}", self.generate_statement(stmt)?));
                }
            } else {
                body_lines.push(format!("    {}", self.generate_statement(stmt)?));
            }
        }
        Ok(format!(
            "pub fn {}({}) -> Quantity {{\n{}\n}}",
            node.name,
            params.join(", "),
            body_lines.join("\n")
        ))
    }

    fn generate_assignment(&self, node: &AssignmentNode) -> Result<String, CodegenError> {
        let value = self.generate_expr(&node.value)?;
        Ok(format!("let {} = {};", node.name, value))
    }

    fn generate_expr(&self, expr: &Expr) -> Result<String, CodegenError> {
        match expr {
            Expr::Quantity(node) => {
                let unit = match &node.unit {
                    Some(u) => format!("\"{}\"", u),
                    None => "\"\"".to_string(),
                };
                if let Some(uncertainty) = node.uncertainty {
                    Ok(format!(
                        "Quantity::with_uncertainty({:?}, {:?}, {})",
                        node.magnitude, uncertainty, unit
                    ))
                } else {
                    Ok(format!(
                        "Quantity::new({:?}, {})",
                        node.magnitude, unit
                    ))
                }
            }
            Expr::Identifier(name) => Ok(name.clone()),
            Expr::BinaryOp { op, left, right } => {
                let left_code = self.generate_expr(left)?;
                let right_code = self.generate_expr(right)?;
                match op {
                    BinaryOp::Add => Ok(format!("{} + {}", left_code, right_code)),
                    BinaryOp::Sub => Ok(format!("{} - {}", left_code, right_code)),
                    BinaryOp::Mul => Ok(format!("{} * {}", left_code, right_code)),
                    BinaryOp::Div => Ok(format!("{} / {}", left_code, right_code)),
                    BinaryOp::Pow => {
                        if let Expr::Quantity(q) = &**right {
                            if q.magnitude.fract() == 0.0 {
                                return Ok(format!("{}.powi({})", left_code, q.magnitude as i32));
                            }
                        }
                        Ok(format!("{}.powf({})", left_code, right_code))
                    }
                    BinaryOp::Convert => Ok(format!("{}.convert_to({})", left_code, right_code)),
                }
            }
            Expr::FunctionCall { name, args } => {
                let mut arg_codes = Vec::new();
                for arg in args {
                    arg_codes.push(self.generate_expr(arg)?);
                }
                Ok(format!("{}({})", name, arg_codes.join(", ")))
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_transpile_function_def() {
        let transpiler = RustTranspiler;
        let ast = Program {
            statements: vec![Statement::FunctionDef(FunctionDefNode {
                name: "kinetic_energy".to_string(),
                params: vec!["m".to_string(), "v".to_string()],
                body_stmts: vec![Statement::Expr(Expr::BinaryOp {
                    op: BinaryOp::Mul,
                    left: Box::new(Expr::BinaryOp {
                        op: BinaryOp::Mul,
                        left: Box::new(Expr::Identifier("m".to_string())),
                        right: Box::new(Expr::BinaryOp {
                            op: BinaryOp::Pow,
                            left: Box::new(Expr::Identifier("v".to_string())),
                            right: Box::new(Expr::Quantity(QuantityNode {
                                magnitude: 2.0,
                                uncertainty: None,
                                is_sigma: false,
                                unit: None,
                            })),
                        }),
                    }),
                    right: Box::new(Expr::Quantity(QuantityNode {
                        magnitude: 0.5,
                        uncertainty: None,
                        is_sigma: false,
                        unit: None,
                    })),
                })],
            })],
        };
        let code = transpiler.generate_program(&ast).unwrap();
        assert!(code.contains("pub fn kinetic_energy(m: Quantity, v: Quantity) -> Quantity"));
        assert!(code.contains("v.powi(2)"));
    }

    #[test]
    fn test_transpile_quantity_with_uncertainty() {
        let transpiler = RustTranspiler;
        let ast = Program {
            statements: vec![Statement::Expr(Expr::Quantity(QuantityNode {
                magnitude: 75.0,
                uncertainty: Some(0.5),
                is_sigma: false,
                unit: Some("kg".to_string()),
            }))],
        };
        let code = transpiler.generate_program(&ast).unwrap();
        assert!(code.contains("Quantity::with_uncertainty(75.0, 0.5, \"kg\")"));
    }
}
