use crate::ast::*;
use crate::codegen::{CodeGenerator, CodegenError};
use std::collections::HashSet;

pub struct RustTranspiler;

impl CodeGenerator for RustTranspiler {
    fn generate_program(&self, program: &Program) -> Result<String, CodegenError> {
        // The stamped version tracks this crate's own version so the banner cannot
        // drift away from the compiler that actually produced the file.
        let mut code = String::from(concat!(
            "// Generated by PhysureScript (PHS) Compiler v", env!("CARGO_PKG_VERSION"), "\n",
            "use physure_core::Quantity;\n\n"
        ));
        let mut top_functions = Vec::new();
        let mut main_statements = Vec::new();
        let mut main_declared_vars = HashSet::new();

        for stmt in &program.statements {
            match stmt {
                Statement::FunctionDef(node) => {
                    top_functions.push(self.generate_function_def(node)?);
                }
                Statement::Assignment(node) => {
                    main_statements.push(format!("    {}", self.generate_assignment(node, &mut main_declared_vars)?));
                    main_statements.push(format!("    println!(\"{}: {{}}\", {});", node.name, node.name));
                }
                Statement::Expr(expr) => {
                    if let Some((kind, a, b)) = super::as_assert_call(expr) {
                        let a_code = self.generate_expr(a)?;
                        let b_code = self.generate_expr(b)?;
                        let method = if kind == "assert" { "phs_assert" } else { "phs_exact_assert" };
                        main_statements.push(format!("    ({}).{}(&({}))?;", a_code, method, b_code));
                    } else {
                        let expr_code = self.generate_expr(expr)?;
                        main_statements.push(format!("    println!(\"{{}}\", {});", expr_code));
                    }
                }
                Statement::While { .. } => {
                    main_statements.push(format!("    {}", self.generate_statement(stmt, &mut main_declared_vars)?));
                }
                _ => {}
            }
        }

        for func in top_functions {
            code.push_str(&func);
            code.push_str("\n\n");
        }

        if !main_statements.is_empty() {
            code.push_str("fn main() -> Result<(), Box<dyn std::error::Error>> {\n");
            code.push_str(&main_statements.join("\n"));
            code.push_str("\n    Ok(())\n}\n");
        }

        Ok(code)
    }
}

impl RustTranspiler {
    fn generate_statement(&self, stmt: &Statement, declared_vars: &mut HashSet<String>) -> Result<String, CodegenError> {
        match stmt {
            Statement::Import(_) => Ok(String::new()),
            Statement::Export(_) => Ok(String::new()),
            Statement::FunctionDef(node) => self.generate_function_def(node),
            Statement::Assignment(node) => self.generate_assignment(node, declared_vars),
            Statement::Expr(expr) => {
                if let Some((kind, a, b)) = super::as_assert_call(expr) {
                    let a_code = self.generate_expr(a)?;
                    let b_code = self.generate_expr(b)?;
                    let method = if kind == "assert" { "phs_assert" } else { "phs_exact_assert" };
                    Ok(format!("({}).{}(&({}))?", a_code, method, b_code))
                } else {
                    self.generate_expr(expr)
                }
            }
            Statement::Return(expr) => Ok(format!("return {};", self.generate_expr(expr)?)),
            Statement::GuardReturn { cond, value } => {
                Ok(format!("if {} {{ return {}; }}", self.generate_expr(cond)?, self.generate_expr(value)?))
            }
            Statement::While { cond, body, .. } => {
                let cond_str = self.generate_expr(cond)?;
                let mut lines = Vec::new();
                for s in body {
                    let stmt_code = self.generate_statement(s, declared_vars)?;
                    if !stmt_code.is_empty() {
                        let stmt_with_semi = if stmt_code.ends_with(';') || stmt_code.ends_with('}') {
                            stmt_code
                        } else {
                            format!("{};", stmt_code)
                        };
                        for line in stmt_with_semi.lines() {
                            lines.push(format!("  {}", line));
                        }
                    }
                }
                Ok(format!("while {} {{\n{}\n}}", cond_str, lines.join("\n")))
            }
        }
    }

    fn generate_function_def(&self, node: &FunctionDefNode) -> Result<String, CodegenError> {
        let mut params = Vec::new();
        for param in &node.params {
            params.push(format!("{}: Quantity", param));
        }
        let mut declared_vars: HashSet<String> = node.params.iter().cloned().collect();
        let last_idx = node.body_stmts.len().saturating_sub(1);
        let mut body_lines = Vec::new();
        for (i, stmt) in node.body_stmts.iter().enumerate() {
            if i == last_idx {
                if let Statement::Expr(ref e) = stmt {
                    body_lines.push(format!("    {}", self.generate_expr(e)?));
                } else {
                    body_lines.push(format!("    {}", self.generate_statement(stmt, &mut declared_vars)?));
                }
            } else {
                body_lines.push(format!("    {}", self.generate_statement(stmt, &mut declared_vars)?));
            }
        }
        Ok(format!(
            "pub fn {}({}) -> Quantity {{\n{}\n}}",
            node.name,
            params.join(", "),
            body_lines.join("\n")
        ))
    }

    fn generate_assignment(&self, node: &AssignmentNode, declared_vars: &mut HashSet<String>) -> Result<String, CodegenError> {
        let value = self.generate_expr(&node.value)?;
        if declared_vars.contains(&node.name) {
            Ok(format!("{} = {};", node.name, value))
        } else {
            declared_vars.insert(node.name.clone());
            Ok(format!("let mut {} = {};", node.name, value))
        }
    }

    fn generate_expr(&self, expr: &Expr) -> Result<String, CodegenError> {
        match expr {
            Expr::Quantity(node) => {
                if let Some(reason) = node.asymmetric_refusal() {
                    return Err(CodegenError::Generic(reason));
                }
                let unit = match &node.unit {
                    Some(u) => format!("\"{}\"", u),
                    None => "\"\"".to_string(),
                };
                if let Some(uncertainty) = node.uncertainty {
                    Ok(format!(
                        "Quantity::with_uncertainty({:?}, {:?}, {}).unwrap()",
                        node.magnitude, uncertainty, unit
                    ))
                } else {
                    Ok(format!(
                        "Quantity::new({:?}, {}).unwrap()",
                        node.magnitude, unit
                    ))
                }
            }
            Expr::Str(text) => {
                // `format!` is the native equivalent. A brace the user wrote as text has to
                // be doubled, or it would be read as a placeholder of its own.
                let parts = super::split_interpolated(text);
                let mut fmt = String::new();
                let mut args = Vec::new();
                for part in &parts {
                    match part {
                        super::StrPart::Text(t) => fmt.push_str(&t.replace('{', "{{").replace('}', "}}")),
                        super::StrPart::Expr(e) => {
                            fmt.push_str("{}");
                            args.push(self.generate_expr(e)?);
                        }
                    }
                }
                Ok(if args.is_empty() {
                    format!("{:?}.to_string()", fmt)
                } else {
                    format!("format!({:?}, {})", fmt, args.join(", "))
                })
            }
            Expr::Identifier(name) => Ok(name.clone()),
            Expr::BinaryOp { op, left, right } => {
                let left_code = self.generate_expr(left)?;
                match op {
                    // Parenthesised like the Python target: without it a nested
                    // operand is re-associated by Rust's own precedence, so
                    // `12 m / (3 s * 2)` emitted as `12 / 3 * 2` and answered 8
                    // where PHS answers 2.
                    //
                    // Operands are borrowed (`&(...)`) rather than moved: `Quantity` has no
                    // `Copy`, so a variable used twice in one expression (`x + 2.0 / x`, which
                    // a convergence loop's body writes routinely) would otherwise fail to
                    // compile with "use of moved value" on its second use.
                    BinaryOp::Add => Ok(format!("(&({}) + &({}))", left_code, self.generate_expr(right)?)),
                    BinaryOp::Sub => Ok(format!("(&({}) - &({}))", left_code, self.generate_expr(right)?)),
                    BinaryOp::Mul => Ok(format!("(&({}) * &({}))", left_code, self.generate_expr(right)?)),
                    BinaryOp::Div => Ok(format!("(&({}) / &({}))", left_code, self.generate_expr(right)?)),
                    BinaryOp::Pow => {
                        if let Expr::Quantity(q) = &**right {
                            if q.magnitude.fract() == 0.0 {
                                return Ok(format!("{}.powi({}).unwrap()", left_code, q.magnitude as i32));
                            }
                        }
                        Ok(format!("{}.powf({}).unwrap()", left_code, self.generate_expr(right)?))
                    }
                    BinaryOp::Convert => {
                        let unit_str = super::expr_to_unit_string(right);
                        Ok(format!("({}).to(\"{}\").unwrap()", left_code, unit_str))
                    }
                    BinaryOp::Range => return Err(super::range_is_not_transpilable()),
                }
            }
            Expr::FunctionCall { name, args, kwargs } => {
                if let Some((op_sym, l, r)) = super::as_comparison_op(expr) {
                    let l_str = self.generate_expr(l)?;
                    let r_str = self.generate_expr(r)?;
                    return Ok(format!("({}.canonical_magnitude() {} {}.canonical_magnitude())", l_str, op_sym, r_str));
                }
                if !kwargs.is_empty() {
                    return Err(CodegenError::Generic(format!(
                        "Named arguments are not supported in Rust codegen (call to '{}')",
                        name
                    )));
                }
                if (name == "assert" || name == "exact_assert") && args.len() == 2 {
                    return Err(CodegenError::Generic(format!(
                        "'{}' can only be used as a standalone statement, not nested inside an expression",
                        name
                    )));
                }
                let mut arg_codes = Vec::new();
                for arg in args {
                    arg_codes.push(self.generate_expr(arg)?);
                }
                Ok(format!("{}({})", name, arg_codes.join(", ")))
            }
            Expr::ForExpr { var, iterable, body } => {
                let it_str = self.generate_expr(iterable)?;
                let body_str = self.generate_expr(body)?;
                Ok(format!("({}).into_iter().map(|{}| {}).collect::<Vec<_>>()", it_str, var, body_str))
            }
        }
    }

    /// Wraps the ordinary transpiled function (renamed `<name>_impl`) in a `#[no_mangle] extern
    /// "C"` shim: flat `f64` params (unit baked in from `param_units` at generation time), flat
    /// `f64` return for a function with no `@requires`/`@ensures`, or a `#[repr(C)]
    /// <Name>Result { value: f64, ok: bool }` for one that has them — running each `@requires`
    /// check before the call and each `@ensures` check after, via the exact same `generate_expr`
    /// path already used for the function body, so compiled and interpreted pass/fail can never
    /// diverge by construction. On the first failing check, the message is stashed in a
    /// thread-local string readable via `<name>_last_error()`, mirroring `errno`/`GetLastError`.
    pub fn generate_export_shim(&self, node: &FunctionDefNode) -> Result<String, CodegenError> {
        let impl_name = format!("{}_impl", node.name);
        let mut impl_node = node.clone();
        impl_node.name = impl_name.clone();
        let impl_fn = self.generate_function_def(&impl_node)?;

        let has_contract = node.decorators.iter().any(|d| d.name == "requires" || d.name == "ensures");

        let params_sig: Vec<String> = node.params.iter().map(|p| format!("{}: f64", p)).collect();
        let mut binds = Vec::new();
        let mut call_args = Vec::new();
        for (i, param) in node.params.iter().enumerate() {
            let unit = node.param_units.get(i).and_then(|u| u.as_deref()).unwrap_or("");
            binds.push(format!("    let {p} = Quantity::new({p}, {u:?}).unwrap();", p = param, u = unit));
            call_args.push(param.clone());
        }
        let binds = binds.join("\n");
        let call_expr = format!("{}({})", impl_name, call_args.join(", "));

        let mut shim = String::new();
        shim.push_str(&impl_fn);
        shim.push_str("\n\n");

        if !has_contract {
            shim.push_str(&format!(
                "#[no_mangle]\npub extern \"C\" fn {name}({params}) -> f64 {{\n{binds}\n    {call}.value.mean()\n}}\n",
                name = node.name,
                params = params_sig.join(", "),
                binds = binds,
                call = call_expr,
            ));
            return Ok(shim);
        }

        let pascal = super::to_pascal_case(&node.name);
        let error_static = format!("{}_LAST_ERROR", node.name.to_uppercase());

        shim.push_str(&format!(
            "#[repr(C)]\npub struct {pascal}Result {{\n    pub value: f64,\n    pub ok: bool,\n}}\n\n",
            pascal = pascal,
        ));
        shim.push_str(&format!(
            "thread_local! {{\n    static {error_static}: std::cell::RefCell<String> = std::cell::RefCell::new(String::new());\n}}\n\n",
            error_static = error_static,
        ));

        let mut body = String::new();
        body.push_str(&binds);
        body.push('\n');
        for dec in &node.decorators {
            if dec.name == "requires" {
                let cond = self.generate_expr(&dec.args[0])?;
                let msg = message_literal(&dec.args[1]);
                body.push_str(&format!(
                    "    if !({cond}) {{\n        {error_static}.with(|e| *e.borrow_mut() = {msg}.to_string());\n        return {pascal}Result {{ value: 0.0, ok: false }};\n    }}\n",
                    cond = cond, error_static = error_static, msg = msg, pascal = pascal,
                ));
            }
        }
        body.push_str(&format!("    let result = {};\n", call_expr));
        for dec in &node.decorators {
            if dec.name == "ensures" {
                let cond = self.generate_expr(&dec.args[0])?;
                let msg = message_literal(&dec.args[1]);
                body.push_str(&format!(
                    "    if !({cond}) {{\n        {error_static}.with(|e| *e.borrow_mut() = {msg}.to_string());\n        return {pascal}Result {{ value: 0.0, ok: false }};\n    }}\n",
                    cond = cond, error_static = error_static, msg = msg, pascal = pascal,
                ));
            }
        }
        body.push_str(&format!("    {pascal}Result {{ value: result.value.mean(), ok: true }}\n", pascal = pascal));

        shim.push_str(&format!(
            "#[no_mangle]\npub extern \"C\" fn {name}({params}) -> {pascal}Result {{\n{body}}}\n\n",
            name = node.name,
            params = params_sig.join(", "),
            pascal = pascal,
            body = body,
        ));

        shim.push_str(&format!(
            "#[no_mangle]\npub extern \"C\" fn {name}_last_error() -> *const std::os::raw::c_char {{\n    {error_static}.with(|e| std::ffi::CString::new(e.borrow().clone()).unwrap_or_default().into_raw())\n}}\n",
            name = node.name,
            error_static = error_static,
        ));

        Ok(shim)
    }
}

/// Renders a decorator's message argument as a Rust string literal. `{:?}` on a `&str` already
/// produces a correctly escaped, double-quoted Rust literal, so no hand-rolled escaping is
/// needed. Every existing `@requires`/`@ensures` message is built as `Expr::Str` (see
/// `decorators.rs`), so the fallback branch is unreached in practice; it exists so a non-literal
/// message can never panic codegen.
fn message_literal(expr: &Expr) -> String {
    match expr {
        Expr::Str(s) => format!("{:?}", s),
        _ => "\"contract violated\"".to_string(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_transpile_function_def() {
        let transpiler = RustTranspiler;
        let ast = Program {
            statements: vec![Statement::FunctionDef(FunctionDefNode {
                name: "kinetic_energy".to_string(),
                params: vec!["m".to_string(), "v".to_string()],
                param_units: vec![None, None],
                body_stmts: vec![Statement::Expr(Expr::BinaryOp {
                    op: BinaryOp::Mul,
                    left: Box::new(Expr::BinaryOp {
                        op: BinaryOp::Mul,
                        left: Box::new(Expr::Identifier("m".to_string())),
                        right: Box::new(Expr::BinaryOp {
                            op: BinaryOp::Pow,
                            left: Box::new(Expr::Identifier("v".to_string())),
                            right: Box::new(Expr::Quantity(QuantityNode {
                                magnitude: 2.0,
                                uncertainty: None,
                                uncertainty_lower: None,
                                is_sigma: false,
                                unit: None,
                            })),
                        }),
                    }),
                    right: Box::new(Expr::Quantity(QuantityNode {
                        magnitude: 0.5,
                        uncertainty: None,
                        uncertainty_lower: None,
                        is_sigma: false,
                        unit: None,
                    })),
                })],
                body_lines: vec![],
                decorators: Vec::new(),
                doc: None,
            })],
            lines: vec![],
        };
        let code = transpiler.generate_program(&ast).unwrap();
        assert!(code.contains("pub fn kinetic_energy(m: Quantity, v: Quantity) -> Quantity"));
        assert!(code.contains("v.powi(2)"));
    }

    #[test]
    fn test_transpile_quantity_with_uncertainty() {
        let transpiler = RustTranspiler;
        let ast = Program {
            statements: vec![Statement::Expr(Expr::Quantity(QuantityNode {
                magnitude: 75.0,
                uncertainty: Some(0.5),
                uncertainty_lower: None,
                is_sigma: false,
                unit: Some("kg".to_string()),
            }))],
            lines: vec![],
        };
        let code = transpiler.generate_program(&ast).unwrap();
        assert!(code.contains("Quantity::with_uncertainty(75.0, 0.5, \"kg\")"));
    }

    #[test]
    fn transpiles_assert_call_to_phs_assert_with_question_mark() {
        let transpiler = RustTranspiler;
        let program = crate::parser::parse_phs("assert(1.0 km, 1000.0 m)").unwrap();
        let code = transpiler.generate_program(&program).unwrap();
        assert!(code.contains(".phs_assert(&"), "expected phs_assert call:\n{code}");
        assert!(code.contains('?'), "expected the call to propagate its Result:\n{code}");
    }

    #[test]
    fn transpiles_exact_assert_call_to_phs_exact_assert() {
        let transpiler = RustTranspiler;
        let program = crate::parser::parse_phs("exact_assert(5.0 m, 5.0 m)").unwrap();
        let code = transpiler.generate_program(&program).unwrap();
        assert!(code.contains(".phs_exact_assert(&"), "expected phs_exact_assert call:\n{code}");
    }

    #[test]
    fn rejects_assert_used_as_a_nested_expression() {
        let transpiler = RustTranspiler;
        let program = crate::parser::parse_phs("x = assert(1.0 m, 1.0 m)").unwrap();
        assert!(transpiler.generate_program(&program).is_err());
    }

    #[test]
    fn test_transpile_for_expr_and_while_stmt_rust() {
        let tp = RustTranspiler;
        let for_expr = Expr::ForExpr {
            var: "x".to_string(),
            iterable: Box::new(Expr::Identifier("items".to_string())),
            body: Box::new(Expr::Identifier("x".to_string())),
        };
        let code_for = tp.generate_expr(&for_expr).unwrap();
        assert_eq!(code_for, "(items).into_iter().map(|x| x).collect::<Vec<_>>()");

        let while_stmt = Statement::While {
            cond: Expr::Identifier("flag".to_string()),
            body: vec![Statement::Return(Expr::Identifier("x".to_string()))],
            body_lines: vec![],
        };
        let code_while = tp.generate_statement(&while_stmt, &mut HashSet::new()).unwrap();
        assert_eq!(code_while, "while flag {\n  return x;\n}");
    }

    #[test]
    fn test_rust_reassignment_in_while_loop() {
        let tp = RustTranspiler;
        let program = crate::parser::parse_phs("i = 0\nwhile i < 5 {\n  i = i + 1\n}").unwrap();
        let code = tp.generate_program(&program).unwrap();
        assert!(code.contains("let mut i = "), "expected mutable declaration:\n{code}");
        assert!(code.contains("i = (&(i) +"), "expected reassignment without redeclaration:\n{code}");
        assert!(!code.contains("let mut i = (&(i) +"), "reassignment should not redeclare inside the loop:\n{code}");
    }

    #[test]
    fn export_shim_bare_function_returns_flat_f64() {
        let node = FunctionDefNode {
            name: "kinetic_energy".to_string(),
            params: vec!["m".to_string(), "v".to_string()],
            param_units: vec![Some("kg".to_string()), Some("m/s".to_string())],
            body_stmts: vec![Statement::Expr(Expr::BinaryOp {
                op: BinaryOp::Mul,
                left: Box::new(Expr::Quantity(QuantityNode {
                    magnitude: 0.5,
                    uncertainty: None,
                    uncertainty_lower: None,
                    is_sigma: false,
                    unit: None,
                })),
                right: Box::new(Expr::Identifier("m".to_string())),
            })],
            body_lines: vec![],
            decorators: vec![],
            doc: None,
        };
        let shim = RustTranspiler.generate_export_shim(&node).unwrap();
        assert!(shim.contains("pub fn kinetic_energy_impl(m: Quantity, v: Quantity) -> Quantity"));
        assert!(shim.contains("pub extern \"C\" fn kinetic_energy(m: f64, v: f64) -> f64"));
        assert!(shim.contains("Quantity::new(m, \"kg\").unwrap()"));
        assert!(shim.contains("kinetic_energy_impl(m, v).value.mean()"));
        assert!(!shim.contains("KineticEnergyResult"));
    }

    #[test]
    fn export_shim_decorated_function_returns_result_struct() {
        let node = FunctionDefNode {
            name: "kinetic_energy".to_string(),
            params: vec!["m".to_string()],
            param_units: vec![Some("kg".to_string())],
            body_stmts: vec![Statement::Expr(Expr::Identifier("m".to_string()))],
            body_lines: vec![],
            decorators: vec![
                DecoratorNode {
                    name: "requires".to_string(),
                    args: vec![
                        Expr::FunctionCall {
                            name: "op_>".to_string(),
                            args: vec![
                                Expr::Identifier("m".to_string()),
                                Expr::Quantity(QuantityNode {
                                    magnitude: 0.0,
                                    uncertainty: None,
                                    uncertainty_lower: None,
                                    is_sigma: false,
                                    unit: Some("kg".to_string()),
                                }),
                            ],
                            kwargs: vec![],
                        },
                        Expr::Str("m must be positive".to_string()),
                    ],
                },
                DecoratorNode {
                    name: "ensures".to_string(),
                    args: vec![
                        Expr::FunctionCall {
                            name: "op_>".to_string(),
                            args: vec![
                                Expr::Identifier("result".to_string()),
                                Expr::Quantity(QuantityNode {
                                    magnitude: 0.0,
                                    uncertainty: None,
                                    uncertainty_lower: None,
                                    is_sigma: false,
                                    unit: Some("kg".to_string()),
                                }),
                            ],
                            kwargs: vec![],
                        },
                        Expr::Str("result must be positive".to_string()),
                    ],
                },
            ],
            doc: None,
        };
        let shim = RustTranspiler.generate_export_shim(&node).unwrap();
        assert!(shim.contains("pub struct KineticEnergyResult"));
        assert!(shim.contains("pub extern \"C\" fn kinetic_energy(m: f64) -> KineticEnergyResult"));
        assert!(shim.contains("\"m must be positive\""));
        assert!(shim.contains("\"result must be positive\""));
        assert!(shim.contains("let result = kinetic_energy_impl(m);"));
        assert!(shim.contains("pub extern \"C\" fn kinetic_energy_last_error() -> *const std::os::raw::c_char"));
    }
}
